let servers=[],channels=[],mainTab='pool',quotaCache={},loadingFiles=new Set(),collapsed=new Set(),editId=null,delId=null,refreshing=new Set(),chRefreshing=new Set(),channelSyncing=new Set(),srvConnecting=new Set(),firstLoad=true,appBooted=false,connectAllPromise=null,autoRefreshSec=60,autoRefreshTimer=null,autoRefreshCountdown=0,autoRefreshCountdownTimer=null,togglingCreds=new Set(),deletingCreds=new Set(),dlCredCtx=null,editChId=null,chSaving=false,cpaView=null,cpaQuery='',credQuery='',channelQuery='',surface=new URLSearchParams(location.search).get('surface')||'popup',srvMenuId=null,chMenuId=null,chKeyId=null,chKeys=[],chKeysLoading=false,chKeyFull={},chKeyShown={},chKeyGroups=[],chKeyEditId=null,dragCard=null,hdrMenuOpen=false;
const memStore={};
let storeSig='';
const STORE_KEYS=['apm_s','apm_ch','apm_tab','apm_font','relay_theme','apm_ar'];
const inShell=window.parent!==window;
const inExtensionPage=/extension:/i.test(location.protocol);
function hasMem(k){return Object.prototype.hasOwnProperty.call(memStore,k)}
function curStoreSig(){return STORE_KEYS.map(k=>k+'='+(hasMem(k)?memStore[k]:'')).join('\n')}
function stGet(k){if(inShell)return hasMem(k)?memStore[k]:null;try{return localStorage.getItem(k)}catch{return hasMem(k)?memStore[k]:null}}
function stSet(k,v){memStore[k]=String(v);if(inShell){window.parent.postMessage({type:'RELAY_STORE_SET',key:k,value:String(v)},'*');return}try{localStorage.setItem(k,v)}catch{}}
function requestShellStore(){if(inShell)window.parent.postMessage({type:'RELAY_STORE_GET'},'*')}
const bc={claude:'bdg-claude',codex:'bdg-codex','gemini-cli':'bdg-gemini_cli',antigravity:'bdg-anti',kimi:'bdg-kimi'};
const EP={
  claude:{url:'https://api.anthropic.com/api/oauth/usage',method:'GET',headers:{'Authorization':'Bearer $TOKEN$','Content-Type':'application/json','anthropic-beta':'oauth-2025-04-20'}},
  codex:{url:'https://chatgpt.com/backend-api/wham/usage',method:'GET',headers:{'Authorization':'Bearer $TOKEN$','Content-Type':'application/json','User-Agent':'codex_cli_rs/0.76.0 (Debian 13.0.0; x86_64) WindowsTerminal'}},
  'gemini-cli':{url:'https://cloudcode-pa.googleapis.com/v1internal:retrieveUserQuota',method:'POST',headers:{'Authorization':'Bearer $TOKEN$','Content-Type':'application/json'}},
  antigravity:{url:'https://daily-cloudcode-pa.googleapis.com/v1internal:fetchAvailableModels',method:'POST',headers:{'Authorization':'Bearer $TOKEN$','Content-Type':'application/json','User-Agent':'antigravity/1.11.5 windows/amd64'}},
  kimi:{url:'https://api.kimi.com/coding/v1/usages',method:'GET',headers:{'Authorization':'Bearer $TOKEN$'}}
};
function np(p){if(!p)return null;const s=String(p).toLowerCase().trim();return{claude:'claude',claudepro:'claude',claude_pro:'claude',codex:'codex',copilot:'codex',gemini:'gemini-cli','gemini-cli':'gemini-cli',gemini_cli:'gemini-cli',antigravity:'antigravity',kimi:'kimi'}[s]||s}
function nai(v){if(!v)return null;if(typeof v==='string'){const t=v.trim();return t||null}return String(v)||null}
function djwt(t){try{const p=t.split('.');if(p.length<2)return null;let b=p[1].replace(/-/g,'+').replace(/_/g,'/');while(b.length%4)b+='=';return JSON.parse(atob(b))}catch{return null}}
function toObj(v){return v&&typeof v==='object'?v:null}
function exCId(f){const id=toObj(f.id_token);return id?.chatgpt_account_id||f.chatgpt_account_id||f.account_id||f.account||null}
function normPlan(v){const raw=String(v||'').trim();if(!raw)return'';const l=raw.toLowerCase(),m={free:'Free',go:'Go',plus:'Plus',pro:'Pro',team:'Team',business:'Business',enterprise:'Enterprise',education:'Education',edu:'Education',max:'Max'};if(m[l])return m[l];const hits=[...new Set(l.replace(/[^a-z0-9]+/g,' ').trim().split(/\s+/).filter(Boolean).map(x=>m[x]).filter(Boolean))];return hits.length===1?hits[0]:''}
function getPlanText(file){const id=toObj(file.id_token),vals=[id?.plan_type,file.plan_type,file.chatgpt_plan_type,file.subscription_type,file.plan];let fallback='';for(const v of vals){const raw=String(v||'').trim();if(!raw)continue;const plan=normPlan(raw);if(plan)return plan;if(!fallback)fallback=raw}return fallback}
function getQuotaPlanText(quota){const raw=String(quota?.data?.plan_type??quota?.data?.planType??'').trim();if(!raw)return'';return normPlan(raw)||raw}
function exGP(f){const a=f.account||'';const m=a.match(/\(([^()]+)\)/g);return m&&m.length?m[m.length-1].replace(/[()]/g,'').trim():(a||'default')}
function ck(s,f){return`${s}::${f}`}
function isRtOnly(f){const v=f?.runtime_only??f?.runtimeOnly;return typeof v==='boolean'?v:typeof v==='string'?v.trim().toLowerCase()==='true':false}
function esc(s){if(!s)return'';const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function jsArg(v){return`'${String(v).replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\n/g,'\\n').replace(/\r/g,'\\r').replace(/</g,'\\x3c')}'`}
function keyDomId(prefix,id){return prefix+'_'+String(id).replace(/[^a-zA-Z0-9_-]/g,'_')}
function maskSecret(v){const s=String(v||'');if(!s)return'••••••••';if(s.includes('****')||s.includes('••••'))return esc(s);if(s.length<=12)return esc(s.slice(0,2)+'****'+s.slice(-2));return esc(s.slice(0,6)+'••••'+s.slice(-6))}
function icon(id){return`<svg class="ico" aria-hidden="true"><use href="#${id}"></use></svg>`}
function ib(cls,label,onclick,disabled=''){return`<button class="b ${cls} icon-btn" onclick="${onclick}" title="${esc(label)}" aria-label="${esc(label)}" ${disabled}>${icon(iconMap[label]||'i-settings')}</button>`}
const iconMap={'浅色':'i-sun','深色':'i-moon','刷新':'i-refresh','侧栏':'i-panel','新增':'i-plus','新增 CPA':'i-plus','新增渠道':'i-plus','凭证':'i-list','密钥':'i-key','API Key':'i-key','设置':'i-settings','更多':'i-more','编辑':'i-edit','删除':'i-trash','返回':'i-arrow-left','下载':'i-download','上传':'i-upload','复制':'i-copy','打开':'i-external','保存':'i-check','取消':'i-x','禁用':'i-ban','启用':'i-play','充值':'i-external','生成':'i-key','添加':'i-plus','关闭':'i-x','显示/隐藏':'i-eye','显示密钥':'i-eye','隐藏密钥':'i-eye-off'};
function iconForLabel(label){const l=String(label||'').replace(/^\+\s*/,'').trim();if(iconMap[l])return iconMap[l];if(/新增|添加/.test(l))return'i-plus';if(/刷新|重试/.test(l))return'i-refresh';if(/编辑/.test(l))return'i-edit';if(/删除|清除/.test(l))return'i-trash';if(/保存|提交|确认/.test(l))return'i-check';if(/取消|关闭/.test(l))return'i-x';if(/下载/.test(l))return'i-download';if(/上传/.test(l))return'i-upload';if(/复制/.test(l))return'i-copy';if(/打开|充值/.test(l))return'i-external';if(/API\s*Key|生成/.test(l))return'i-key';if(/凭证/.test(l))return'i-list';if(/设置/.test(l))return'i-settings';if(/更多/.test(l))return'i-more';if(/禁用/.test(l))return'i-ban';if(/隐藏/.test(l))return'i-eye-off';if(/显示/.test(l))return'i-eye';if(/启用|OAuth|Claude|Codex|Gemini|Antigravity/.test(l))return'i-play';return'i-settings'}
function iconizeButtons(){document.querySelectorAll('button.b:not(.main-tab):not(.keep-icon),a.b:not(.keep-icon)').forEach(el=>{const label=(el.getAttribute('aria-label')||el.getAttribute('title')||el.textContent||'操作').replace(/^\+\s*/,'').trim()||'操作';if(el.dataset.iconized===label)return;el.dataset.iconized=label;el.setAttribute('aria-label',label);el.setAttribute('title',label);if(el.querySelector('.ld'))return;el.classList.add('icon-only','icon-btn');el.innerHTML=icon(iconForLabel(label))})}
let iconizeTimer=null;function scheduleIconize(){clearTimeout(iconizeTimer);iconizeTimer=setTimeout(iconizeButtons,0)}
function fmtK(n){if(n==null)return'-';if(n>=1e6)return(n/1e6).toFixed(1)+'M';if(n>=1e3)return(n/1e3).toFixed(1)+'K';return String(n)}
function fmtResetTime(v){if(!v)return'';if(typeof v==='number'){if(v>1e12)return new Date(v).toLocaleString();if(v>1e9)return new Date(v*1000).toLocaleString();const m=Math.floor(v/60),s=v%60;return m>0?`${m}分${s}秒后`:`${s}秒后`}return fmtTs(String(v))}
function fmtTs(ts){if(!ts)return'-';try{const d=new Date(ts);if(isNaN(d.getTime())){const t=String(ts).match(/(\d+)/);if(t)return t[1];return ts}return d.toLocaleString()}catch{return ts}}
function maskUrl(u){try{const r=new URL(u);return r.host+r.pathname.replace(/\/$/,'')}catch{return u}}
function maskKey(ep){if(!ep)return ep;let s=String(ep).trim();const m=s.match(/^(GET|POST|PUT|PATCH|DELETE|OPTIONS|HEAD)\s+/i);let method=m?m[0].trim():'';if(m)s=s.substring(m[0].length).trim();const masked=s.length>12?s.slice(0,4)+'****'+s.slice(-4):s.slice(0,2)+'****';return(method?method+' ':'')+masked}
function maskEp(ep){try{if(!ep)return ep;let s=String(ep).trim();const m=s.match(/^(GET|POST|PUT|PATCH|DELETE|OPTIONS|HEAD)\s+/i);let method=m?m[0].trim():'';if(m)s=s.substring(m[0].length).trim();s=s.replace(/([a-f0-9]{6,})/gi,m=>m.slice(0,4)+'****');s=s.replace(/(key|token|secret|password|api[-_]?key)=([^&?\s]{3})[^&?\s]*/gi,'$1=$2****');try{const r=new URL(s);let p=r.pathname.replace(/\/$/,'');p=p.replace(/([a-f0-9]{6,})/gi,m=>m.slice(0,4)+'****');if(r.search){const sp=new URLSearchParams(r.search);for(const k of sp.keys()){const v=sp.get(k);if(v&&v.length>4)sp.set(k,v.slice(0,3)+'****')}p+='?'+sp.toString().replace(/(key|token|secret|password|api[-_]?key)=([^&]{3})[^&]*/gi,'$1=$2****')}return(method?method+' ':'')+r.host+p}catch{return(method?method+' ':'')+s}}catch{return ep}}
function getPS(f){const s={};f.forEach(x=>{const p=np(x.provider)||'?';s[p]=(s[p]||0)+1});return s}

function encStore(d){try{const j=JSON.stringify(d);const b=btoa(unescape(encodeURIComponent(j)));return b.split('').reverse().join('')}catch{return JSON.stringify(d)}}
function decStore(s){try{if(!s)return null;const r=s.split('').reverse().join('');const d=decodeURIComponent(escape(atob(r)));return JSON.parse(d)}catch{try{return JSON.parse(s)}catch{return null}}}
function cleanSecretText(v){return String(v||'').replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/\s+/g,'').trim()}
function cpaAuth(srv){srv.key=cleanSecretText(srv.key);return`Bearer ${srv.key}`}
function load(){const s=decStore(stGet('apm_s'))||[];servers=s.map(x=>({id:x.id,name:x.name,url:normCpaUrl(x.url),key:cleanSecretText(x.key),status:null,files:[]}));const c=decStore(stGet('apm_ch'))||[];channels=c.map(x=>{const type=x.type||'newapi',url=normBaseUrl(x.url||'',type);return{id:x.id,name:x.name,type,url,username:x.username||'',password:x.password||'',manual:cleanManual(x.manual||{},url),userId:x.userId||'',token:x.token||'',tokenAt:Number(x.tokenAt)||0,status:null,data:null,error:null}})}
function save(){stSet('apm_s',encStore(servers.map(x=>({id:x.id,name:x.name,url:x.url,key:cleanSecretText(x.key)}))))}
function persistChannels(){stSet('apm_ch',encStore(channels.map(x=>({id:x.id,name:x.name,type:x.type,url:x.url,username:x.username,password:x.password,manual:x.manual||{},userId:x.userId||'',token:x.token||'',tokenAt:x.tokenAt||0}))))}
function loadQC(){quotaCache={}}
function saveQC(){}
function renderCur(){const focus=saveFocus();renderHdr();renderCred();renderChannels();setMainTab(mainTab,true);restoreFocus(focus);scheduleIconize()}
function renderData(){const focus=saveFocus();mainTab==='channel'?renderChannels():renderCred();restoreFocus(focus);scheduleIconize()}

function clearDragMarks(){document.querySelectorAll('.sortable-card.dragging,.sortable-card.drag-over').forEach(x=>x.classList.remove('dragging','drag-over'))}
function cardDragStart(kind,id,ev){if(ev.target.closest('button,a,input,select,textarea,.srv-menu')){ev.preventDefault();return}dragCard={kind,id:String(id)};srvMenuId=null;chMenuId=null;document.querySelectorAll('.srv-menu').forEach(x=>x.classList.add('hidden'));ev.currentTarget.classList.add('dragging');ev.dataTransfer.effectAllowed='move';ev.dataTransfer.setData('text/plain',kind+':'+id)}
function cardDragOver(kind,id,ev){if(!dragCard||dragCard.kind!==kind||dragCard.id===String(id))return;ev.preventDefault();ev.dataTransfer.dropEffect='move';document.querySelectorAll('.sortable-card.drag-over').forEach(x=>x.classList.remove('drag-over'));ev.currentTarget.classList.add('drag-over')}
function cardDragLeave(ev){ev.currentTarget.classList.remove('drag-over')}
function cardDragEnd(){clearDragMarks();dragCard=null}
function dropCard(kind,id,ev){ev.preventDefault();ev.stopPropagation();const raw=ev.dataTransfer.getData('text/plain')||'',parts=raw.split(':'),from=dragCard?.id||parts[1]||'';clearDragMarks();dragCard=null;if((parts[0]&&parts[0]!==kind)||!from||from===String(id))return;const list=kind==='cpa'?servers:channels,fromIdx=list.findIndex(x=>String(x.id)===String(from)),toIdx=list.findIndex(x=>String(x.id)===String(id));if(fromIdx<0||toIdx<0||fromIdx===toIdx)return;const item=list.splice(fromIdx,1)[0];list.splice(toIdx,0,item);kind==='cpa'?save():persistChannels();showToast('排序已保存');renderCur()}

function renderHdr(){document.body.classList.toggle('surface-sidepanel',surface==='sidepanel');document.getElementById('sideBtn')?.classList.toggle('side-hidden',surface==='sidepanel')}
function toggleHdrMenu(ev){ev?.stopPropagation?.();const el=document.getElementById('hdrMenu');hdrMenuOpen=!(el&&el.classList.contains('hidden')===false);document.querySelectorAll('.srv-menu').forEach(x=>x.classList.add('hidden'));srvMenuId=null;chMenuId=null;if(el)el.classList.toggle('hidden',!hdrMenuOpen)}
function hideHdrMenu(){hdrMenuOpen=false;document.getElementById('hdrMenu')?.classList.add('hidden')}
function exportCfg(){hideHdrMenu();const data={version:1,exportedAt:new Date().toISOString(),servers:servers.map(x=>({id:x.id,name:x.name,url:x.url,key:cleanSecretText(x.key)})),channels:channels.map(x=>({id:x.id,name:x.name,type:x.type,url:x.url,username:x.username,password:x.password,manual:x.manual||{}})),prefs:{tab:mainTab,font:stGet('apm_font')||'md',theme:stGet('relay_theme')||'light',autoRefresh:stGet('apm_ar')||String(autoRefreshSec||0)}};saveBlob(`relay-hub-config-${Date.now()}.json`,new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));showToast('配置已导出')}
function importCfgPick(){hideHdrMenu();if(!confirm('导入配置会覆盖当前 CPA、渠道和界面设置，是否继续？'))return;document.getElementById('cfgFile')?.click()}
async function importCfgFile(input){const file=input?.files?.[0];if(!file)return;try{const raw=JSON.parse(await file.text()),sv=Array.isArray(raw?.servers)?raw.servers:[],ch=Array.isArray(raw?.channels)?raw.channels:[],prefs=raw?.prefs||{};servers=sv.map(x=>({id:String(x.id||Date.now()+Math.random()),name:String(x.name||'').trim(),url:normCpaUrl(x.url||''),key:cleanSecretText(x.key),status:null,files:[]})).filter(x=>x.name&&x.url&&x.key);channels=ch.map(x=>{const type=x.type==='sub2api'?'sub2api':'newapi',url=normBaseUrl(x.url||'',type);return{id:String(x.id||('ch_'+Date.now()+Math.random())),name:String(x.name||'').trim(),type,url,username:String(x.username||''),password:String(x.password||''),manual:cleanManual(x.manual||{},url),userId:'',token:'',tokenAt:0,status:null,data:null,error:null}}).filter(x=>x.name&&x.url&&x.username&&x.password);save();persistChannels();if(prefs.font)stSet('apm_font',String(prefs.font));if(prefs.theme)applyTheme(String(prefs.theme));if(prefs.tab){mainTab=String(prefs.tab)==='channel'?'channel':'pool';stSet('apm_tab',mainTab)}if(prefs.autoRefresh!=null)stSet('apm_ar',String(prefs.autoRefresh));loadQC();renderCur();await connectAll();setAutoRefresh(stGet('apm_ar')||'60');showToast('配置已导入')}catch(e){showToast('导入失败: '+(e.message||e))}finally{if(input)input.value=''}}
function saveFocus(){const el=document.activeElement;if(!el||!el.id||!['cpaSearch','credSearch','channelSearch'].includes(el.id))return null;return{id:el.id,start:el.selectionStart,end:el.selectionEnd}}
function restoreFocus(f){if(!f)return;setTimeout(()=>{const el=document.getElementById(f.id);if(!el)return;el.focus();try{el.setSelectionRange(f.start??el.value.length,f.end??el.value.length)}catch{}},0)}
function keepFocus(fn){const f=saveFocus();const r=fn();restoreFocus(f);return r}
function setMainTab(t,skipSave){const nt=t||'pool',changed=mainTab!==nt;mainTab=nt;if(!skipSave&&changed)cpaView=null;document.getElementById('tab_pool')?.classList.toggle('active',mainTab==='pool');document.getElementById('tab_channel')?.classList.toggle('active',mainTab==='channel');document.getElementById('poolPanel')?.classList.toggle('active',mainTab==='pool');document.getElementById('channelPanel')?.classList.toggle('active',mainTab==='channel');if(!skipSave){stSet('apm_tab',mainTab);renderCred();renderChannels()}}
function applyTheme(t){const light=t==='light';document.body.classList.toggle('theme-light',light);document.body.classList.toggle('theme-dark',!light);const b=document.getElementById('themeBtn');if(b){b.title=light?'切换到深色':'切换到浅色';b.setAttribute('aria-label',b.title);b.innerHTML=icon(light?'i-moon':'i-sun')}stSet('relay_theme',light?'light':'dark')}
function toggleTheme(){applyTheme(document.body.classList.contains('theme-light')?'dark':'light')}
function openSidePanel(){if(window.parent===window){showToast('请在扩展弹窗中打开侧边栏');return}window.parent.postMessage({type:'RELAY_OPEN_SIDEPANEL'},'*')}

function syncAutoRefreshControls(v){['arSelect'].forEach(id=>{const el=document.getElementById(id);if(el)el.dataset.interval=String(v)})}
function setAutoRefresh(v){autoRefreshSec=parseInt(v)||0;syncAutoRefreshControls(autoRefreshSec);clearInterval(autoRefreshCountdownTimer);autoRefreshCountdownTimer=null;autoRefreshCountdown=autoRefreshSec;updateCountdown();if(autoRefreshSec>0)startArCountdown()}
function changeAutoRefresh(v){if(v==='live')return;const n=parseInt(v)||0;stSet('apm_ar',String(n));setAutoRefresh(n);showToast(n>0?'自动刷新已设置':'自动刷新已关闭')}
function startArCountdown(){if(autoRefreshCountdownTimer)return;autoRefreshCountdownTimer=setInterval(()=>{autoRefreshCountdown--;if(autoRefreshCountdown<=0){autoRefreshCountdown=0;updateCountdown();clearInterval(autoRefreshCountdownTimer);autoRefreshCountdownTimer=null;setRefreshBusy();connectAll().finally(()=>{autoRefreshCountdown=autoRefreshSec;updateCountdown();if(autoRefreshSec>0)startArCountdown()});return}updateCountdown()},1000)}
function fmtCountdown(v){if(v==null||v<0)return'0s';return v>=60&&v%60===0?(v/60)+'m':v+'s'}
function updateCountdown(){['arBtnText'].forEach(id=>{const btn=document.getElementById(id);if(btn)btn.innerHTML=icon('i-refresh')});const s=document.getElementById('arSelect');if(s){const v=autoRefreshSec>0?fmtCountdown(autoRefreshCountdown):'关';let o=s.querySelector('option[data-live="1"]');if(!o){o=document.createElement('option');o.dataset.live='1';s.prepend(o)}o.value='live';o.textContent=v;s.value='live'}}
function setRefreshBusy(){['arBtnText'].forEach(id=>{const btn=document.getElementById(id);if(btn)btn.innerHTML='<span class="ld" style="width:14px;height:14px;border-width:2px"></span>'})}
function manualRefresh(){clearInterval(autoRefreshCountdownTimer);autoRefreshCountdownTimer=null;setRefreshBusy();connectAll().finally(()=>{autoRefreshCountdown=autoRefreshSec;updateCountdown();if(autoRefreshSec>0)startArCountdown()})}

document.addEventListener('DOMContentLoaded',()=>{new MutationObserver(scheduleIconize).observe(document.body,{childList:true,subtree:true});document.addEventListener('click',()=>{document.querySelectorAll('.srv-menu').forEach(x=>x.classList.add('hidden'));srvMenuId=null;chMenuId=null;hideHdrMenu()});if(inShell){renderHdr();requestShellStore();return}bootApp()});
function bootApp(){if(appBooted)return;appBooted=true;load();loadQC();mainTab=stGet('apm_tab')||'pool';const fs=stGet('apm_font')||'md';document.body.className='font-size-'+fs;applyTheme(stGet('relay_theme')||'light');const ar=stGet('apm_ar')||'60';syncAutoRefreshControls(ar);firstLoad=true;renderCur();connectAll().then(()=>setAutoRefresh(ar)).catch(e=>showToast('加载失败: '+(e.message||e)))}
async function connectAll(scope){if(connectAllPromise)return connectAllPromise;connectAllPromise=(async()=>{const jobs=[];if(!scope||scope==='cpa')jobs.push(...servers.map(s=>connectSrv(s)));if(!scope||scope==='channel')jobs.push(...channels.map(c=>connectChannel(c)));await Promise.allSettled(jobs);firstLoad=false;refreshing.clear();chRefreshing.clear();renderData()})().finally(()=>{connectAllPromise=null});return connectAllPromise}
async function connectSrv(srv){if(srvConnecting.has(srv.id))return;srvConnecting.add(srv.id);srv.url=normCpaUrl(srv.url);try{const u=cpaUrl(srv,'/auth-files',{_ts:Date.now()}),r=await cpaHttp(u,{headers:{'Authorization':cpaAuth(srv),'Cache-Control':'no-cache','Pragma':'no-cache'}}),d=cpaJson(r);srv.files=d.files||[];srv.status='online';srv.error=null}catch(e){srv.status='offline';srv.files=[];srv.error=e.message||String(e)}finally{srvConnecting.delete(srv.id)}}
async function refSQ(sid){if(refreshing.has(sid))return;refreshing.add(sid);renderCur();try{const s=servers.find(x=>x.id===sid);if(!s||s.status!=='online')return;await Promise.allSettled((s.files||[]).filter(f=>!f.disabled).map(f=>refQ(s,f)));renderCur()}finally{refreshing.delete(sid);renderCur()}}
async function refQ(srv,file){const k=ck(srv.id,file.name);loadingFiles.add(k);renderCur();try{const p=np(file.provider),ai=nai(file.auth_index||file.authIndex||file.id||file.name),ep=EP[p];if(!ai||!ep){quotaCache[k]={data:null,error:!ep?'不支持: '+p:'缺authIndex',ts:Date.now()};saveQC();return}const h={...ep.headers};let body;if(p==='codex'){const aid=exCId(file);if(!aid){quotaCache[k]={data:null,error:'缺account_id',ts:Date.now()};saveQC();return}h['Chatgpt-Account-Id']=aid}else if(p==='gemini-cli')body=JSON.stringify({project:exGP(file)});else if(p==='antigravity')body=JSON.stringify({project:'bamboo-precept-lgxtn'});if(ep.method==='GET'&&p!=='codex')body=undefined;const r=await cpaHttp(cpaUrl(srv,'/api-call'),{method:'POST',headers:{'Authorization':cpaAuth(srv),'Content-Type':'application/json'},body:JSON.stringify({authIndex:ai,method:ep.method,url:ep.url,header:h,data:body})});const res=cpaJson(r),sc=res.status_code??res.statusCode??0,raw=res.body??res.bodyText;const parsed=typeof raw==='string'&&raw.trim()?JSON.parse(raw):raw;quotaCache[k]=sc>=200&&sc<300?{data:parsed,error:null,ts:Date.now()}:{data:null,error:`HTTP ${sc}`,ts:Date.now()};saveQC()}catch(e){quotaCache[k]={data:null,error:e.message,ts:Date.now()};saveQC()}finally{loadingFiles.delete(k);renderCur()}}
function toggleCol(id){collapsed.has(id)?collapsed.delete(id):collapsed.add(id);renderCred()}
function toggleAllCol(){const allCol=collapsed.size===servers.length&&servers.length;servers.forEach(s=>{allCol?collapsed.delete(s.id):collapsed.add(s.id)});renderCred()}

/* ============ CREDENTIALS PANEL ============ */
function fileActive(f){return(f.status==='ready'||f.status==='active')&&!f.disabled}
function serverStats(files){files=files||[];return{total:files.length,active:files.filter(fileActive).length,disabled:files.filter(f=>f.disabled).length,error:files.filter(f=>!fileActive(f)&&!f.disabled).length,providers:getPS(files)}}
function providerChips(ps){return Object.entries(ps||{}).map(([p,c])=>`<span class="bdg ${bc[p]||''}">${esc(p)} ${c}</span>`).join('')}
function cpaSearchText(s){return [s.name,s.url,...(s.files||[]).flatMap(f=>[f.name,f.email,f.account,f.provider])].join(' ').toLowerCase()}
function renderCpaOverview(){const online=servers.filter(s=>s.status==='online').length,files=servers.flatMap(s=>s.files||[]),st=serverStats(files),q=globalQuotaSummary();return`<div class="overview"><div class="ov-grid cpa-overview-grid"><div><div class="ov-k">CPA</div><div class="ov-v">${online}/${servers.length}</div></div><div><div class="ov-k">凭证</div><div class="ov-v" title="凭证总数">${st.total}</div></div><div><div class="ov-k">凭证状态</div>${credStateNums(st)}</div><div><div class="ov-k">限额（最低）</div>${renderQuotaChips(q.items,'暂无已刷新限额')}</div></div></div>`}

function credNums(st){return`<div class="cred-nums" title="总数 / 正常 / 异常 / 禁用"><span>${st.total}</span><em>/</em><span class="num-ok">${st.active}</span><em>/</em><span class="num-err">${st.error}</span><em>/</em><span class="num-warn">${st.disabled}</span></div>`}
function credStateNums(st){return`<div class="cred-nums" title="正常 / 异常 / 禁用"><span class="num-ok">${st.active}</span><em>/</em><span class="num-err">${st.error}</span><em>/</em><span class="num-warn">${st.disabled}</span></div>`}
function renderQuotaChips(items,empty='暂无可汇总数据'){if(!items.length)return`<span class="quota-chip muted">${empty}</span>`;let chips=items.slice(0,5).map(x=>`<span class="quota-chip ${x.min<30?'low':''}" title="${esc(x.label)} · 最低 ${x.min.toFixed(0)}% · 平均 ${x.avg.toFixed(0)}% · ${x.count} 个凭证">${esc(x.label)} <strong>${x.min.toFixed(0)}%</strong></span>`).join('');if(items.length>5)chips+=`<span class="quota-chip muted">+${items.length-5}</span>`;return chips}
function globalQuotaSummary(){const groups={};servers.forEach(s=>srvQuotaSummary(s).items.forEach(x=>{const g=groups[x.label]||(groups[x.label]={label:x.label,count:0,sum:0,min:101});g.count+=x.count;g.sum+=x.avg*x.count;g.min=Math.min(g.min,x.min)}));return{items:Object.values(groups).map(g=>({label:g.label,count:g.count,avg:g.sum/g.count,min:g.min})).sort((a,b)=>a.min-b.min||b.count-a.count)}}
function renderCred(){
  const el=document.getElementById('credPanel');
  if(cpaView){renderCredDetail();return}
  const q=cpaQuery.trim().toLowerCase();
  let list=q?servers.filter(s=>cpaSearchText(s).includes(q)):servers;
  const bar=`${renderCpaOverview()}<div class="search-row"><input class="fi" id="cpaSearch" value="${esc(cpaQuery)}" oninput="keepFocus(()=>{cpaQuery=this.value;renderCred()})" placeholder="搜索 CPA / 地址 / 凭证 / 提供商">${ib('bp','新增 CPA','showAddModal()')}</div>`;
  if(!servers.length){el.innerHTML=bar+'<div class="empty">暂无 CPA，点击添加 CPA</div>';return}
  if(!list.length){el.innerHTML=bar+'<div class="empty">没有匹配的 CPA</div>';return}
  el.innerHTML=bar+list.map(s=>renderCredSrv(s,'all','all')).join('');
}
function renderFC(file){const p=np(file.provider),pc=bc[p]||'',act=(file.status==='ready'||file.status==='active')&&!file.disabled,sc=act?'bdg-ok':file.disabled?'bdg-warn':'bdg-err',st=file.disabled?'已禁用':file.status||'未知',acc=file.email||file.account||'-',k=ck(file._sid,file.name),c=quotaCache[k],pt=(p==='codex'?getQuotaPlanText(c):'')||getPlanText(file),il=loadingFiles.has(k),tl=togglingCreds.has(k),hep=!!EP[p],canRef=hep&&!file.disabled,lrf=file.last_refresh||file.lastRefreshedAt||'',sm=String(file.status_message||file.statusMessage||'').trim(),showSm=sm&&sm.toLowerCase()!=='ok'&&sm!==st,smc=act?'var(--t2)':file.disabled?'var(--warn)':'var(--err)',tgl=file.disabled?'启用':'禁用',tglBusy=file.disabled?'启用中':'禁用中';let qH='';if(il)qH='<div class="qload"><span class="ld"></span>获取中</div>';else if(c)qH=renderQC(p,c);else if(file.disabled)qH='<div class="qempty" style="cursor:default">凭证已禁用</div>';else if(canRef)qH=`<div class="qempty" onclick="event.stopPropagation();refSingle('${file._sid}','${esc(file.name)}')">${act?'点击获取限额':'点击重试刷新'}</div>`;else if(!hep)qH='<div class="qempty" style="cursor:default">不支持限额查询</div>';else qH='<div class="qempty" style="cursor:default">账户不可用</div>';return`<div class="fc"><div class="fc-top"><div class="fc-line1"><span class="fc-name" title="${esc(file.name)}">${esc(file.name)}</span><div class="fc-acts">${canRef?`<button class="b bs" onclick="event.stopPropagation();refSingle('${file._sid}','${esc(file.name)}')" ${il||tl?'disabled':''}>${il?'<span class="ld" style="width:8px;height:8px;border-width:1.5px"></span>':'刷新'}</button>`:''}<button class="b ${file.disabled?'bp':'bd'}" onclick="event.stopPropagation();setCredDisabled('${file._sid}','${esc(file.name)}',${file.disabled?'false':'true'})" ${tl?'disabled':''}>${tl?`<span class="ld" style="width:8px;height:8px;border-width:1.5px"></span> ${tglBusy}`:tgl}</button><button class="b bs" onclick="event.stopPropagation();dlFile('${file._sid}','${esc(file.name)}')" ${tl?'disabled':''}>下载</button></div></div><div class="fc-line2"><span class="bdg ${pc}">${esc(p||'-')}</span>${pt?`<span class="bdg bdg-plan">${esc(fmtPlan(pt))}</span>`:''}<span class="bdg ${sc}">${st}</span>${lrf?`<span style="font-size:10px;color:var(--t2)" title="Token 刷新时间">刷新 ${fmtTs(lrf)}</span>`:''}</div><div class="fc-acc">${esc(acc)}</div>${showSm?`<div style="font-size:11px;color:${smc};margin-top:4px;word-break:break-word" title="${esc(sm)}">${esc(sm)}</div>`:''}<div class="fc-sep"></div></div><div class="fc-body">${qH}</div></div>`}

function renderCredSrv(srv,pf,sf){
  const connecting=srv.status===null,on=srv.status==='online',files=srv.files||[],ac=files.filter(f=>(f.status==='ready'||f.status==='active')&&!f.disabled).length,dc=files.filter(f=>f.disabled).length,ec=files.filter(f=>f.status!=='ready'&&f.status!=='active'&&!f.disabled).length;
  const ps=getPS(files),pb=Object.entries(ps).map(([p,c])=>`<span class="bdg ${bc[p]||''}">${esc(p)} ${c}</span>`).join(''),site=esc(cpaManagementUrl(srv));
  const quota=renderSrvQuotaSummary(srv);
  return`<div class="ss sortable-card" draggable="true" ondragstart="cardDragStart('cpa',${jsArg(srv.id)},event)" ondragover="cardDragOver('cpa',${jsArg(srv.id)},event)" ondragleave="cardDragLeave(event)" ondrop="dropCard('cpa',${jsArg(srv.id)},event)" ondragend="cardDragEnd()"><div class="sb cpa-head"><div class="cpa-main"><div class="cpa-title"><span class="dot ${on?'on':'off'}"></span><span class="cpa-name">${esc(srv.name)}</span><a class="site-link cpa-site" href="${site}" target="_blank" rel="noopener noreferrer">${esc(maskUrl(srv.url))}</a></div><div class="cpa-meta">${credNums({total:files.length,active:ac,error:ec,disabled:dc})}${pb}</div>${quota}</div><div class="s-act cpa-actions">${ib('bs','凭证',`showCredView('${srv.id}')`,!on?'disabled':'')}${ib('bs','API Key',`showApiKeyModal('${srv.id}')`,!on?'disabled':'')}${refreshing.has(srv.id)?`<button class="b bs icon-btn" disabled title="刷新限额" aria-label="刷新限额"><span class="ld" style="width:14px;height:14px;border-width:2px"></span></button>`:ib('bs','刷新限额',`refSQ('${srv.id}')`,!on?'disabled':'')}${ib('bs','更多',`toggleSrvMenu('${srv.id}',event)`)}${renderSrvMenu(srv.id)}</div></div></div>`}

function renderSrvMenu(id){return`<div class="srv-menu hidden" id="srvMenu_${id}"><button class="srv-menu-item" onclick="showSrvSettings('${id}')">${icon('i-settings')}<span>设置</span></button><button class="srv-menu-item" onclick="showEditModal('${id}')">${icon('i-edit')}<span>编辑</span></button><button class="srv-menu-item danger" onclick="delSrv('${id}')">${icon('i-trash')}<span>删除</span></button></div>`}
function toggleSrvMenu(id,ev){ev?.stopPropagation?.();const el=document.getElementById('srvMenu_'+id),next=el&&!el.classList.contains('hidden')?null:id;document.querySelectorAll('.srv-menu').forEach(x=>x.classList.add('hidden'));srvMenuId=next;chMenuId=null;if(next)document.getElementById('srvMenu_'+next)?.classList.remove('hidden')}

function renderSrvQuotaSummary(srv){const q=srvQuotaSummary(srv);return`<div class="quota-line"><span class="quota-label">限额（最低）</span>${renderQuotaChips(q.items)}</div>`}
function srvQuotaSummary(srv){const groups={},files=srv.files||[];let total=0,pending=0,errors=0;files.forEach(f=>{const p=np(f.provider),k=ck(srv.id,f.name);if(!EP[p]||f.disabled)return;total++;const c=quotaCache[k];if(!c){pending++;return}if(c.error){errors++;return}quotaWindows(p,c.data).forEach(w=>{const g=groups[w.label]||(groups[w.label]={label:w.label,count:0,sum:0,min:101});g.count++;g.sum+=w.remaining;g.min=Math.min(g.min,w.remaining)})});const items=Object.values(groups).map(g=>({label:g.label,count:g.count,avg:g.sum/g.count,min:g.min})).sort((a,b)=>a.min-b.min||b.count-a.count);return{total,pending,errors,items}}
function quotaWindows(p,d){const out=[];if(!d)return out;if(p==='claude'){Object.entries(d.limits||{}).forEach(([k,v])=>{if(v&&typeof v==='object'&&'utilization'in v)out.push({label:fCWL(k),remaining:Math.max(0,100-(Number(v.utilization)||0))})})}else if(p==='codex'){const rl=d.rate_limit||d.rateLimit||{};Object.entries(rl).forEach(([k,v])=>{if(!v||typeof v!=='object')return;const used=Number(v.used_percent??v.usedPercent);if(!Number.isFinite(used))return;out.push({label:fCWL(k.replace(/_window$/,'').replace(/Window$/,'')),remaining:Math.max(0,100-used)})})}else if(p==='gemini-cli'){(d.buckets||[]).forEach(b=>out.push({label:b.model_id||b.modelId||'Gemini',remaining:Math.max(0,Number(b.remaining_fraction??b.remainingFraction??0)*100)}))}else if(p==='antigravity'){Object.entries(d.models||{}).forEach(([k,v])=>{if(v&&typeof v==='object')out.push({label:k,remaining:Math.max(0,Number(v.remaining_fraction??v.remainingFraction??0)*100)})})}else if(p==='kimi'&&Array.isArray(d)){d.forEach(i=>{const l=Number(i.limit)||0,u=Number(i.used)||0;out.push({label:i.label||i.model||'Kimi',remaining:l>0?Math.max(0,100-u/l*100):100})})}return out.filter(x=>Number.isFinite(x.remaining))}

function showCredView(id){cpaView=id;credQuery='';renderCred()}
function hideCredView(){cpaView=null;srvMenuId=null;renderCred()}
function credSearchText(f){return [f.name,f.email,f.account,f.provider,getPlanText(f)].join(' ').toLowerCase()}
function renderCredDetail(){const el=document.getElementById('credPanel'),s=servers.find(x=>x.id===cpaView);if(!s){cpaView=null;renderCred();return}const files=(s.files||[]).map(f=>({...f,_sid:s.id})),st=serverStats(files),q=credQuery.trim().toLowerCase();let ff=q?files.filter(f=>credSearchText(f).includes(q)):files;const head=`<div class="sub-head">${ib('bs back-btn','返回','hideCredView()')}<div style="min-width:0;flex:1"><div class="sub-title">${esc(s.name)} 凭证</div><div class="tm" style="font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(maskUrl(s.url))} · 凭证 ${st.total} · 正常 ${st.active} · 异常 ${st.error} · 禁用 ${st.disabled}</div></div></div><div class="search-row"><input class="fi" id="credSearch" value="${esc(credQuery)}" oninput="keepFocus(()=>{credQuery=this.value;renderCred()})" placeholder="搜索凭证 / 账号 / 提供商">${ib('bp','新增',`showAddCredModal('${s.id}')`,s.status!=='online'?'disabled':'')}${refreshing.has(s.id)?`<button class="b bs icon-btn" disabled title="刷新" aria-label="刷新"><span class="ld" style="width:14px;height:14px;border-width:2px"></span></button>`:ib('bs','刷新',`refSQ('${s.id}')`,s.status!=='online'?'disabled':'')}</div>`;if(!ff.length){el.innerHTML=head+'<div class="empty">没有匹配的凭证</div>';return}const order=['claude','codex','gemini-cli','antigravity','kimi'];const groups={};ff.forEach(f=>{const p=np(f.provider)||'unknown';(groups[p]||(groups[p]=[])).push(f)});const keys=[...order.filter(p=>groups[p]),...Object.keys(groups).filter(p=>!order.includes(p))];el.innerHTML=head+keys.map(p=>`<div class="fsec"><div class="fsec-h"><span class="bdg ${bc[p]||''}">${esc(p)}</span><span class="bdg">${groups[p].length}</span></div><div class="fg">${groups[p].map(renderFC).join('')}</div></div>`).join('')}

function renderFC(file){
  const p=np(file.provider),pc=bc[p]||'',act=(file.status==='ready'||file.status==='active')&&!file.disabled,sc=act?'bdg-ok':file.disabled?'bdg-warn':'bdg-err',st=file.disabled?'已禁用':file.status||'未知',acc=file.email||file.account||'-',k=ck(file._sid,file.name),c=quotaCache[k],pt=(p==='codex'?getQuotaPlanText(c):'')||getPlanText(file),il=loadingFiles.has(k),tl=togglingCreds.has(k),dl=deletingCreds.has(k),hep=!!EP[p],canRef=hep&&!file.disabled,lrf=file.last_refresh||file.lastRefreshedAt||'',sm=String(file.status_message||file.statusMessage||'').trim(),showSm=sm&&sm.toLowerCase()!=='ok'&&sm!==st,smc=act?'var(--t2)':file.disabled?'var(--warn)':'var(--err)',tgl=file.disabled?'启用':'禁用',tglBusy=file.disabled?'启用中':'禁用中',src=String(file.source||'').trim().toLowerCase(),rt=isRtOnly(file),canDel=!rt&&src!=='memory',delTitle=canDel?'删除凭证':rt?'运行时凭证不支持删除':'当前凭证不支持删除';
  let qH='';
  if(il)qH='<div class="qload"><span class="ld"></span>获取中</div>';
  else if(c)qH=renderQC(p,c);
  else if(file.disabled)qH='<div class="qempty" style="cursor:default">凭证已禁用</div>';
  else if(canRef)qH=`<div class="qempty" onclick="event.stopPropagation();refSingle('${file._sid}','${esc(file.name)}')">${act?'点击获取限额':'点击重试刷新'}</div>`;
  else if(!hep)qH='<div class="qempty" style="cursor:default">不支持限额查询</div>';
  else qH='<div class="qempty" style="cursor:default">账户不可用</div>';
  const dlAct=p==='codex'?`showDlCredModal('${file._sid}','${esc(file.name)}','${esc(p)}')`:`dlFile('${file._sid}','${esc(file.name)}')`;
  return`<div class="fc"><div class="fc-top"><div class="fc-line1"><span class="fc-name" title="${esc(file.name)}">${esc(file.name)}</span><div class="fc-acts">${canRef?`<button class="b bs" onclick="event.stopPropagation();refSingle('${file._sid}','${esc(file.name)}')" ${il||tl||dl?'disabled':''}>${il?'<span class="ld" style="width:8px;height:8px;border-width:1.5px"></span>':'刷新'}</button>`:''}<button class="b ${file.disabled?'bp':'bd'}" onclick="event.stopPropagation();setCredDisabled('${file._sid}','${esc(file.name)}',${file.disabled?'false':'true'})" ${tl||dl?'disabled':''}>${tl?`<span class="ld" style="width:8px;height:8px;border-width:1.5px"></span> ${tglBusy}`:tgl}</button><button class="b bs" onclick="event.stopPropagation();${dlAct}" ${tl||dl?'disabled':''}>下载</button><button class="b bd" onclick="event.stopPropagation();delCred('${file._sid}','${esc(file.name)}')" title="${esc(delTitle)}" ${!canDel||il||tl||dl?'disabled':''}>${dl?'<span class="ld" style="width:8px;height:8px;border-width:1.5px"></span> 删除中':'删除'}</button></div></div><div class="fc-line2"><span class="bdg ${pc}">${esc(p||'-')}</span>${pt?`<span class="bdg bdg-plan">${esc(fmtPlan(pt))}</span>`:''}<span class="bdg ${sc}">${st}</span>${lrf?`<span style="font-size:10px;color:var(--t2)" title="Token 刷新时间">刷新 ${fmtTs(lrf)}</span>`:''}</div><div class="fc-acc">${esc(acc)}</div>${showSm?`<div style="font-size:11px;color:${smc};margin-top:4px;word-break:break-word" title="${esc(sm)}">${esc(sm)}</div>`:''}${rt?'<div style="font-size:11px;color:var(--t2);margin-top:4px">运行时凭证不支持删除</div>':''}<div class="fc-sep"></div></div><div class="fc-body">${qH}</div></div>`}

function renderQC(p,c){if(c.error)return`<div class="qe">错误: ${esc(c.error)}</div>`;if(!c.data)return'<div class="qempty" style="cursor:default">暂无数据</div>';if(p==='claude')return rCl(c.data);if(p==='codex')return rCo(c.data);if(p==='gemini-cli')return rGe(c.data);if(p==='antigravity')return rAn(c.data);if(p==='kimi')return rKi(c.data);return'<div class="qempty" style="cursor:default">不支持</div>'}
function rCl(d){const w=[];Object.entries(d.limits||{}).forEach(([k,v])=>{if(v&&typeof v==='object'&&'utilization'in v){const u=v.utilization||0,r=Math.max(0,100-u),c=u>70?'h':u>30?'m':'l';w.push(`<div class="qi"><div class="qih"><span class="ql">${fCWL(k)}</span><span class="qv" style="color:${r<30?'var(--err)':'inherit'}">${r.toFixed(0)}%</span></div><div class="pbar"><div class="pfill ${c}" style="width:${r}%"></div></div>${v.resets_at?`<div class="qm">重置于 ${fmtTs(v.resets_at)}</div>`:''}</div>`)}});return w.join('')||'<div class="qempty" style="cursor:default">暂无</div>'}
function rCo(d){const rl=d.rate_limit||d.rateLimit||{},w=[];const pw=rl.primary_window||rl.primaryWindow;if(pw){const u=pw.used_percent||pw.usedPercent||0,r=100-u,c=u>70?'h':u>30?'m':'l';const rt=pw.reset_at||pw.reset_time||pw.reset_at_timestamp;w.push(`<div class="qi"><div class="qih"><span class="ql">5小时</span><span class="qv" style="color:${r<30?'var(--err)':'inherit'}">${r.toFixed(0)}%</span></div><div class="pbar"><div class="pfill ${c}" style="width:${r}%"></div></div>${rt?`<div class="qm">恢复于 ${fmtResetTime(rt)}</div>`:''}</div>`)}const sw=rl.secondary_window||rl.secondaryWindow;if(sw){const u=sw.used_percent||sw.usedPercent||0,r=100-u,c=u>70?'h':u>30?'m':'l';const rt=sw.reset_at||sw.reset_time||sw.reset_at_timestamp;w.push(`<div class="qi"><div class="qih"><span class="ql">周</span><span class="qv" style="color:${r<30?'var(--err)':'inherit'}">${r.toFixed(0)}%</span></div><div class="pbar"><div class="pfill ${c}" style="width:${r}%"></div></div>${rt?`<div class="qm">恢复于 ${fmtResetTime(rt)}</div>`:''}</div>`)}return w.join('')||'<div class="qempty" style="cursor:default">暂无</div>'}
function rGe(d){const bs=d.buckets||[];if(!bs.length)return'<div class="qempty" style="cursor:default">暂无</div>';return bs.slice(0,5).map(b=>{const r=(b.remaining_fraction??b.remainingFraction??0)*100,c=r<30?'h':r<70?'m':'l';const rt=b.resetTime||b.reset_time;return`<div class="qi"><div class="qih"><span class="ql" style="max-width:130px;overflow:hidden;text-overflow:ellipsis">${esc(b.model_id||b.modelId||'?')}</span><span class="qv" style="color:${r<30?'var(--err)':'inherit'}">${r.toFixed(0)}%</span></div><div class="pbar"><div class="pfill ${c}" style="width:${r}%"></div></div>${rt?`<div class="qm">恢复于 ${fmtResetTime(rt)}</div>`:''}</div>`}).join('')}
function rAn(d){if(!d?.models)return'<div class="qempty" style="cursor:default">暂无</div>';return Object.entries(d.models).slice(0,5).map(([k,v])=>{if(!v||typeof v!=='object')return'';const p=(v.remaining_fraction??v.remainingFraction??0)*100,c=p<30?'h':p<70?'m':'l';const rt=v.resetTime||v.reset_time;return`<div class="qi"><div class="qih"><span class="ql" style="max-width:130px;overflow:hidden;text-overflow:ellipsis">${esc(k)}</span><span class="qv" style="color:${p<30?'var(--err)':'inherit'}">${p.toFixed(0)}%</span></div><div class="pbar"><div class="pfill ${c}" style="width:${p}%"></div></div>${rt?`<div class="qm">恢复于 ${fmtResetTime(rt)}</div>`:''}</div>`}).filter(Boolean).join('')||'<div class="qempty" style="cursor:default">暂无</div>'}
function rKi(d){if(!Array.isArray(d))return'<div class="qempty" style="cursor:default">暂无</div>';return d.slice(0,5).map(i=>{const u=i.used||0,l=i.limit||0,r=l>0?Math.max(0,100-(u/l*100)):100,c=r<30?'h':r<70?'m':'l';return`<div class="qi"><div class="qih"><span class="ql">${esc(i.label||i.model||'?')}</span><span class="qv" style="color:${r<30?'var(--err)':'inherit'}">${r.toFixed(0)}%</span></div><div class="pbar"><div class="pfill ${c}" style="width:${r}%"></div></div>${l>0?`<div class="qm">${u}/${l}</div>`:''}</div>`}).join('')||'<div class="qempty" style="cursor:default">暂无</div>'}
function fCWL(k){return{primary:'5小时',secondary:'周',five_hour:'5h',seven_day:'7天',seven_day_oauth_apps:'OAuth 7天',seven_day_opus:'Opus 7天',seven_day_sonnet:'Sonnet 7天',seven_day_cowork:'Cowork 7天',monthly:'月限',month:'月限',monthly_limit:'月限',iguana_necktie:'Pro限时'}[k]||k.replace(/_/g,' ')}
function fmtPlan(p){return normPlan(p)||String(p||'').trim()}

function refSingle(sid,fn){const s=servers.find(x=>x.id===sid);if(!s)return;const f=(s.files||[]).find(x=>x.name===fn);if(!f)return;refQ(s,f)}
function showToast(msg){const t=document.getElementById('toast');t.innerHTML=`<span class="ld" style="width:12px;height:12px;border-width:2px"></span>${msg}`;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2000)}
function hideDlCredModal(){document.getElementById('dlCredModal').classList.add('hidden');dlCredCtx=null}
function showDlCredModal(sid,fn,p){if(np(p)!=='codex'){dlFile(sid,fn);return}dlCredCtx={sid,fn};const msg=document.getElementById('dlCredMsg');if(msg)msg.textContent=`选择下载 ${fn} 的 CPA凭证文件，或转换为 Codex CLI 使用的 auth.json 格式。`;document.getElementById('dlCredModal').classList.remove('hidden')}
function saveBlob(fn,blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=fn;a.click();setTimeout(()=>URL.revokeObjectURL(u),0)}
async function fetchCredResp(sid,fn){const s=servers.find(x=>x.id===sid);if(!s)throw new Error('服务端不存在');return cpaHttp(cpaUrl(s,'/auth-files/download',{name:fn,_ts:Date.now()}),{headers:{'Authorization':cpaAuth(s),'Cache-Control':'no-cache','Pragma':'no-cache'},responseType:'base64'})}
async function dlFile(sid,fn){try{const r=await fetchCredResp(sid,fn);saveBlob(fn,cpaBlob(r,r.headers?.['content-type']||'application/octet-stream'))}catch(e){alert('下载失败: '+e.message)}}
function toCodexAuthJson(raw){const src=raw&&typeof raw.tokens==='object'&&raw.tokens?raw.tokens:raw||{},idToken=String(src.id_token||'').trim(),accessToken=String(src.access_token||'').trim(),refreshToken=String(src.refresh_token||'').trim(),accountId=(src.account_id??src.chatgpt_account_id??exCId(raw))||null;if(!idToken||!accessToken||!refreshToken)throw new Error('当前凭证不包含完整的 Codex OAuth Token');const out={OPENAI_API_KEY:null,tokens:{id_token:idToken,access_token:accessToken,refresh_token:refreshToken,account_id:accountId},last_refresh:raw?.last_refresh||raw?.lastRefresh||null};if(raw?.auth_mode)out.auth_mode=raw.auth_mode;if(raw?.agent_identity)out.agent_identity=raw.agent_identity;return out}
async function downloadCredOriginal(){const c=dlCredCtx;if(!c)return;hideDlCredModal();await dlFile(c.sid,c.fn)}
async function downloadCredCodex(){const c=dlCredCtx;if(!c)return;hideDlCredModal();try{const r=await fetchCredResp(c.sid,c.fn),raw=JSON.parse(cpaTextFromBase64(r)),out=toCodexAuthJson(raw);saveBlob('auth.json',new Blob([JSON.stringify(out,null,2)],{type:'application/json'}))}catch(e){showToast('转换下载失败: '+e.message)}}
async function setCredDisabled(sid,fn,disabled){const s=servers.find(x=>x.id===sid),k=ck(sid,fn),act=disabled?'禁用':'启用';if(!s||s.status!=='online'||togglingCreds.has(k))return;if(!confirm(`确定要${act}凭证 "${fn}" 吗？`))return;togglingCreds.add(k);renderCur();try{await cpaHttp(cpaUrl(s,'/auth-files/status'),{method:'PATCH',headers:{'Authorization':cpaAuth(s),'Content-Type':'application/json'},body:JSON.stringify({name:fn,disabled})});showToast(disabled?'已禁用':'已启用');await connectSrv(s)}catch(e){showToast(act+'失败: '+e.message)}finally{togglingCreds.delete(k);renderCur()}}
async function delCred(sid,fn){const s=servers.find(x=>x.id===sid),k=ck(sid,fn),f=s?.files?.find(x=>x.name===fn),src=String(f?.source||'').trim().toLowerCase();if(!s||s.status!=='online'||deletingCreds.has(k)||togglingCreds.has(k)||loadingFiles.has(k))return;if(isRtOnly(f)||src==='memory'){showToast('运行时凭证不支持删除');return}if(!confirm(`确定要删除凭证 "${fn}" 吗？`))return;deletingCreds.add(k);renderCur();try{await cpaHttp(cpaUrl(s,'/auth-files',{name:fn}),{method:'DELETE',headers:{'Authorization':cpaAuth(s)}});delete quotaCache[k];loadingFiles.delete(k);showToast('已删除');await connectSrv(s)}catch(e){showToast('删除失败: '+e.message)}finally{deletingCreds.delete(k);renderCur()}}
function showAddModal(){editId=null;document.getElementById('mt2').textContent='添加 CPA';document.getElementById('sn').value='';document.getElementById('su').value='';document.getElementById('sk').value='';document.getElementById('sModal').classList.remove('hidden')}
function showEditModal(id){srvMenuId=null;const s=servers.find(x=>x.id===id);if(!s)return;editId=id;document.getElementById('mt2').textContent='编辑 CPA';document.getElementById('sn').value=s.name;document.getElementById('su').value=s.url;document.getElementById('sk').value=s.key;document.getElementById('sModal').classList.remove('hidden')}
function hideSModal(){document.getElementById('sModal').classList.add('hidden');editId=null}
function cleanUrlText(u){return String(u||'').trim().replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/\s+/g,'')}
function stripTrailingSlash(u){return cleanUrlText(u).replace(/\/+$/,'')}
function withDefaultScheme(u,scheme){const s=cleanUrlText(u);if(!s)return'';if(s.startsWith('//'))return scheme+':'+s;return !/^[a-z][a-z0-9+.-]*:\/\//i.test(s)?scheme+'://'+s:s}
function setDefaultPort(u,port){try{const r=new URL(u);if(!r.port)r.port=String(port);return r.toString().replace(/\/+$/,'')}catch{return u&&!u.match(/:\d+(\/|$)/)?u+':'+port:u}}
function joinUrl(base,path,query){const b=stripTrailingSlash(base),p='/'+String(path||'').replace(/^\/+/,''),u=b+p;if(!query)return u;const qs=new URLSearchParams();Object.entries(query).forEach(([k,v])=>{if(v!==undefined&&v!==null)qs.set(k,String(v))});const s=qs.toString();return s?u+'?'+s:u}
function normHttpUrl(u,scheme='https'){return stripTrailingSlash(withDefaultScheme(u,scheme))}
function normCpaUrl(u){let s=cleanUrlText(u).replace(/\/v0\/management\/?$/,'').replace(/\/+$/,'');if(!s)return'';return setDefaultPort(normHttpUrl(s,'http'),8317)}
function cpaUrl(srv,path,query){srv.url=normCpaUrl(srv.url);return joinUrl(srv.url,'/v0/management/'+String(path||'').replace(/^\/+/,''),query)}
function cpaEndpointUrl(srv){return normCpaUrl(srv.url)}
function cpaManagementUrl(srv){return joinUrl(cpaEndpointUrl(srv),'/management.html')}
function hrefUrl(u,base=''){const s=cleanUrlText(u);if(!s)return'';if(s.startsWith('//'))return'https:'+s;if(/^https?:\/\//i.test(s))return s;if(base)return joinUrl(base,s);return normHttpUrl(s,'https')}
function saveSrv(){const n=document.getElementById('sn').value.trim(),u=document.getElementById('su').value.trim(),k=cleanSecretText(document.getElementById('sk').value);if(!n||!u||!k){alert('请填写名称、地址和管理密钥');return}let nu=normCpaUrl(u),target=null;if(editId){const s=servers.find(x=>x.id===editId);if(s){s.name=n;s.url=nu;s.key=k;s.status=null;s.files=[];target=s}}else{target={id:Date.now().toString(),name:n,url:nu,key:k,status:null,files:[]};servers.push(target)}save();hideSModal();renderCur();if(target)connectSrv(target).then(()=>renderCur())}
function delSrv(id){srvMenuId=null;const s=servers.find(x=>x.id===id);if(!s)return;document.getElementById('dmsg').textContent=`确定要删除 "${s.name}" 吗？`;delId=id;document.getElementById('dModal').classList.remove('hidden')}
function hideDModal(){document.getElementById('dModal').classList.add('hidden');delId=null}
function confirmDel(){if(delId){servers=servers.filter(s=>s.id!==delId);save();showToast('CPA 已删除');renderCur()}hideDModal()}

let addCredSrvId=null,oauthPollTimer=null,oauthState=null,oauthProviderName='',oauthProviderId='';
const OAUTH_PROVIDERS=[
  {id:'anthropic',name:'Claude',path:'/anthropic-auth-url'},
  {id:'codex',name:'Codex',path:'/codex-auth-url'},
  {id:'gemini-cli',name:'Gemini CLI',path:'/gemini-cli-auth-url'},
  {id:'antigravity',name:'Antigravity',path:'/antigravity-auth-url'}
];
function showAddCredModal(sid){addCredSrvId=sid;const s=servers.find(x=>x.id===sid);if(!s)return;document.getElementById('addCredSrv').textContent='— '+s.name;document.getElementById('oauthBtns').innerHTML=OAUTH_PROVIDERS.map(p=>`<button class="b bs bsm" onclick="startOAuth('${p.id}','${p.path}','${p.name}')">${p.name}</button>`).join('');document.getElementById('credFile').value='';document.getElementById('oauthStep1').classList.remove('hidden');document.getElementById('oauthStep2').classList.add('hidden');document.getElementById('addCredModal').classList.remove('hidden')}
function hideAddCredModal(){document.getElementById('addCredModal').classList.add('hidden');clearInterval(oauthPollTimer);oauthPollTimer=null;oauthState=null;oauthProviderName='';oauthProviderId='';addCredSrvId=null}
async function startOAuth(pid,path,name){const s=servers.find(x=>x.id===addCredSrvId);if(!s)return;try{const r=await cpaHttp(cpaUrl(s,path,{is_webui:true}),{headers:{'Authorization':cpaAuth(s)}}),d=cpaJson(r);const url=d.url||d.auth_url||d.authUrl;if(!url)throw new Error('No URL');oauthState=d.state||null;oauthProviderName=name;oauthProviderId=pid;document.getElementById('oauthProvider').textContent=name;document.getElementById('oauthUrl').textContent=url;document.getElementById('oauthPolling').innerHTML='<span class="ld" style="width:10px;height:10px;border-width:1.5px"></span> 等待授权中...';document.getElementById('callbackUrl').value='';document.getElementById('oauthStep1').classList.add('hidden');document.getElementById('oauthStep2').classList.remove('hidden');clearInterval(oauthPollTimer);if(oauthState){oauthPollTimer=setInterval(()=>pollOAuth(s),3000)}}catch(e){showToast('OAuth 启动失败: '+e.message)}}
async function pollOAuth(s){if(!oauthState)return;try{const r=await cpaHttp(cpaUrl(s,'/get-auth-status',{state:oauthState}),{headers:{'Authorization':cpaAuth(s)}}),d=cpaJson(r);if(d.status==='ok'){clearInterval(oauthPollTimer);oauthPollTimer=null;document.getElementById('oauthPolling').innerHTML='<span style="color:var(--ok)">✓ 授权成功</span>';showToast(oauthProviderName+' 授权成功');await connectSrv(s);renderCur()}else if(d.status==='error'){clearInterval(oauthPollTimer);oauthPollTimer=null;document.getElementById('oauthPolling').innerHTML=`<span style="color:var(--err)">✗ 授权失败: ${esc(d.error||'未知错误')}</span>`}}catch{}}
function copyOAuthUrl(){copyText(document.getElementById('oauthUrl').textContent)}
function fallbackCopy(t){const ta=document.createElement('textarea');ta.value=t;ta.style.cssText='position:fixed;left:-9999px';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');showToast('已复制')}catch{showToast('复制失败')}document.body.removeChild(ta)}
function copyText(t){if(inShell){window.parent.postMessage({type:'RELAY_COPY_TEXT',text:String(t||'')},'*');return}if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(t).then(()=>showToast('已复制')).catch(()=>fallbackCopy(t))}else fallbackCopy(t)}
function endpointRow(url){return`<div class="endpoint-row"><div><div class="endpoint-label">端点 URL</div><code class="endpoint-url">${esc(url)}</code></div>${ib('bs','复制',`copyText(${jsArg(url)})`)}</div>`}
function openOAuthUrl(){const u=document.getElementById('oauthUrl').textContent;window.open(u,'_blank','noopener,noreferrer')}
function cancelOAuth(){clearInterval(oauthPollTimer);oauthPollTimer=null;oauthState=null;oauthProviderId='';document.getElementById('oauthStep2').classList.add('hidden');document.getElementById('oauthStep1').classList.remove('hidden')}
async function submitCallback(){const s=servers.find(x=>x.id===addCredSrvId);if(!s)return;const url=cleanUrlText(document.getElementById('callbackUrl').value);if(!url){showToast('请输入回调 URL');return}const providerMap={'gemini-cli':'gemini'};const provider=providerMap[oauthProviderId]||oauthProviderId;try{await cpaHttp(cpaUrl(s,'/oauth-callback'),{method:'POST',headers:{'Authorization':cpaAuth(s),'Content-Type':'application/json'},body:JSON.stringify({provider,redirect_url:url,state:oauthState||''})});showToast('回调提交成功');clearInterval(oauthPollTimer);oauthPollTimer=null;document.getElementById('oauthPolling').innerHTML='<span style="color:var(--ok)">✓ 授权成功</span>';await connectSrv(s);renderCur()}catch(e){showToast('回调提交失败: '+e.message)}}
async function uploadCredFile(){const s=servers.find(x=>x.id===addCredSrvId);if(!s)return;const fi=document.getElementById('credFile');if(!fi.files||!fi.files.length){showToast('请选择文件');return}try{const mp=await multipartFileBody('file',fi.files[0]);await cpaHttp(cpaUrl(s,'/auth-files'),{method:'POST',headers:{'Authorization':cpaAuth(s),'Content-Type':`multipart/form-data; boundary=${mp.boundary}`},bodyBase64:mp.bodyBase64});showToast('上传成功');await connectSrv(s);renderCur()}catch(e){showToast('上传失败: '+e.message)}}

/* ============ UPSTREAM CHANNELS ============ */
function normBaseUrl(u,type){let s=normHttpUrl(u,'https');if(!s)return'';if(type==='sub2api')s=s.replace(/\/api\/v1\/?$/,'');else s=s.replace(/\/api\/?$/,'');return stripTrailingSlash(s)}
function chAuthHeaders(c){const h={'Content-Type':'application/json','Cache-Control':'no-cache','Pragma':'no-cache'};const t=String(c.token||'').trim();if(t)h.Authorization=/^Bearer\s+/i.test(t)?t:'Bearer '+t;if(c.type==='newapi'&&c.userId)h['New-Api-User']=String(c.userId).trim();return h}
async function chReq(c,path,opt={}){c.url=normBaseUrl(c.url,c.type);const res=await chHttp(joinUrl(c.url,path),{method:opt.method||'GET',headers:{...chAuthHeaders(c),...(opt.headers||{})},body:opt.body||null});const text=res.body;let j=text;if(typeof text==='string'&&text){try{j=JSON.parse(text)}catch{j=text}}if(!res.ok){const msg=j&&typeof j==='object'&&(j.message||j.detail)||typeof j==='string'&&j;throw new Error(`HTTP ${res.status}${msg?': '+msg:''}`)}if(j&&typeof j==='object'&&'code'in j){if(j.code!==0)throw new Error(j.message||j.detail||'请求失败');return j.data}if(j&&typeof j==='object'&&'success'in j){if(!j.success)throw new Error(j.message||'请求失败');return 'data'in j?j.data:j}return j}
function unwrapItems(d){if(Array.isArray(d))return d;if(Array.isArray(d?.items))return d.items;if(Array.isArray(d?.data?.items))return d.data.items;return[]}
function chErr(e){const msg=e&&e.message?String(e.message):String(e||'未知错误');if(/HTTP\s*401/.test(msg))return'HTTP 401: 登录会话无效或用户标识不匹配，请检查账号密码后重新保存渠道';if(/HTTP\s*429/.test(msg))return'HTTP 429: 站点限流，已减少重复请求，请稍后手动刷新';return msg}
function isRateLimited(c){return c.type==='newapi'&&/HTTP\s*429/.test(String(c.error||''))&&Date.now()-(c.updatedAt||0)<60000}
function pickUserId(x){const d=x&&typeof x==='object'?x:null;return d?.id??d?.user_id??d?.userId??d?.data?.id??d?.data?.user_id??d?.data?.userId??d?.user?.id??''}
function todaySecRange(){const d=new Date();d.setHours(0,0,0,0);return{start:Math.floor(d.getTime()/1000),end:Math.floor(Date.now()/1000)}}
function todayDateRange(){const d=new Date(),s=new Date(d);s.setHours(0,0,0,0);const f=x=>x.toISOString().slice(0,10);return{start:f(s),end:f(d)}}
function sumArr(a,k){return(a||[]).reduce((n,x)=>n+(Number(x?.[k])||0),0)}
function fmtNum(n,d=2){if(n==null||n===''||Number.isNaN(Number(n)))return'-';const v=Number(n);if(Math.abs(v)>=1000000)return(v/1000000).toFixed(1)+'M';if(Math.abs(v)>=1000)return(v/1000).toFixed(1)+'K';return Number.isInteger(v)?String(v):v.toFixed(d)}
function fmtMoney(n){if(n==null||n===''||Number.isNaN(Number(n)))return'-';return '$'+Number(n).toFixed(2)}
function fmtRatio(v){if(v==null||v===''||Number.isNaN(Number(v)))return'-';return Number(v).toFixed(4).replace(/0+$/,'').replace(/\.$/,'')+'x'}
function fmtNewQuota(raw,status){if(raw==null||Number.isNaN(Number(raw)))return'-';const q=Number(raw),qpu=Number(status?.quota_per_unit)||500000,typ=String(status?.quota_display_type||'USD').toUpperCase();if(typ==='TOKENS')return fmtNum(q,0)+' 点';const usd=q/qpu;if(typ==='CNY')return '¥'+(usd*(Number(status?.usd_exchange_rate)||1)).toFixed(2);if(typ==='CUSTOM'){const sym=status?.custom_currency_symbol||'¤',rate=Number(status?.custom_currency_exchange_rate)||1;return sym+(usd*rate).toFixed(2)}return fmtMoney(usd)}
function cleanManual(m,baseUrl=''){const out={};const rr=String(m?.rechargeRatio??'').trim();if(rr)out.rechargeRatio=rr;const topup=cleanUrlText(m?.topupUrl??'');if(topup)out.topupUrl=/^https?:\/\//i.test(topup)||!baseUrl?normHttpUrl(topup,'https'):joinUrl(baseUrl,topup);return out}
function chCanAuto(c){return !!(String(c.url||'').trim()&&String(c.username||'').trim()&&String(c.password||'').trim())}
function applyManual(d,c){const m=c.manual||{};return{...(d||{}),manual:m,topupUrlManual:m.topupUrl,rechargeRatioManual:m.rechargeRatio}}
function pickToken(x){if(!x)return'';if(typeof x==='string')return x;return x.token||x.access_token||x.accessToken||x.access_token_string||x.accessTokenString||x.jwt||x.id_token||x.key||x.api_key||x.data?.token||x.data?.access_token||x.data?.accessToken||x.data?.jwt||x.user?.token||x.user?.access_token||''}
const CH_PROXY_BASE=`${location.protocol}//${location.hostname}:8787`,chPending={};
window.addEventListener('message',e=>{const m=e.data;if(!m)return;if(m.type==='RELAY_STORE_DATA'&&m.data){Object.assign(memStore,m.data);const sig=curStoreSig();if(sig===storeSig)return;storeSig=sig;if(!appBooted)bootApp();else if(!connectAllPromise&&!srvConnecting.size&&!channelSyncing.size){load();mainTab=stGet('apm_tab')||mainTab;applyTheme(stGet('relay_theme')||'light');syncAutoRefreshControls(stGet('apm_ar')||autoRefreshSec);renderCur()}return}if(m.type==='RELAY_COPY_TEXT_RESULT'){showToast(m.ok?'已复制':('复制失败: '+(m.error||'未知错误')));return}if(m.type==='RELAY_OPEN_SIDEPANEL_RESULT'&&m.response&&!m.response.ok){showToast('打开侧边栏失败: '+(m.response.error||'未知错误'));return}if(m.type!=='CPA_CHANNEL_FETCH_RESULT'||!m.id||!chPending[m.id])return;chPending[m.id](m.response);delete chPending[m.id]});
async function extFetch(payload){if(window.parent===window)return null;const id='req_'+Date.now()+'_'+Math.random().toString(16).slice(2);return new Promise((resolve,reject)=>{chPending[id]=resolve;window.parent.postMessage({type:'CPA_CHANNEL_FETCH',id,payload},'*');setTimeout(()=>{if(chPending[id]){delete chPending[id];reject(new Error('扩展请求超时'))}},30000)})}
function bytesToBase64(bytes){let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
async function cpaHttp(url,opt={}){const payload={kind:'cpa',url,method:opt.method||'GET',headers:opt.headers||{},body:opt.body||null,bodyBase64:opt.bodyBase64||'',responseType:opt.responseType||''};const j=await extFetch(payload);if(!j)throw new Error(inExtensionPage?'CPA 请求未经过扩展外壳，请关闭旧页面后从扩展弹窗或侧边栏重新打开':'CPA 请求需要通过浏览器扩展后台发送');if(!j.ok){let msg=j.error||`HTTP ${j.status}`;if(j.body)msg+=' '+String(j.body).slice(0,160);throw new Error(msg)}return j}
function cpaJson(res){const text=res.body;return typeof text==='string'&&text?JSON.parse(text):text}
function cpaBlob(res,type='application/octet-stream'){const bin=Uint8Array.from(atob(res.body||''),c=>c.charCodeAt(0));return new Blob([bin],{type})}
function cpaTextFromBase64(res){const bytes=Uint8Array.from(atob(res.body||''),c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
async function fileToBase64(file){return bytesToBase64(new Uint8Array(await file.arrayBuffer()))}
async function multipartFileBody(name,file){const boundary='----RelayHub'+Date.now().toString(16)+Math.random().toString(16).slice(2),safeName=file.name.replace(/"/g,''),pre=`--${boundary}\r\nContent-Disposition: form-data; name="${name}"; filename="${safeName}"\r\nContent-Type: ${file.type||'application/octet-stream'}\r\n\r\n`,post=`\r\n--${boundary}--\r\n`;return{boundary,bodyBase64:await fileToBase64(new Blob([pre,file,post]))}}
async function chExtFetch(payload){return extFetch(payload)}
async function chHttp(url,opt={}){const payload={kind:'channel',url,method:opt.method||'GET',headers:opt.headers||{},body:opt.body||null};let j=null;try{j=await chExtFetch(payload)}catch(e){throw e}if(!j){const r=await fetch(`${CH_PROXY_BASE}/proxy`,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});j=await r.json();if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`)}if(!j.ok&&!j.status)throw new Error(j.error||'请求失败');return j}
async function chLoginReq(c,path,body){c.url=normBaseUrl(c.url,c.type);const res=await chHttp(joinUrl(c.url,path),{method:'POST',headers:{'Content-Type':'application/json','Cache-Control':'no-cache','Pragma':'no-cache'},body:JSON.stringify(body)});let j=res.body; if(typeof j==='string'&&j){try{j=JSON.parse(j)}catch{}}if(!res.ok){const msg=j&&typeof j==='object'&&(j.message||j.detail)||typeof j==='string'&&j;throw new Error(`HTTP ${res.status}${msg?': '+msg:''}`)}if(j&&typeof j==='object'&&'code'in j&&j.code!==0)throw new Error(j.message||j.detail||'登录失败');if(j&&typeof j==='object'&&'success'in j&&!j.success)throw new Error(j.message||'登录失败');return j?.data??j}
async function loginChannel(c){let res;if(c.type==='sub2api'){const body={email:c.username,password:c.password};let last=null;for(const p of ['/api/v1/auth/login','/api/v1/user/login','/api/v1/login']){try{res=await chLoginReq(c,p,body);break}catch(e){last=e}}if(!res&&last)throw last;const t=pickToken(res);if(!t)throw new Error('登录成功但未返回 token');c.token=t;c.tokenAt=Date.now()}else{res=await chLoginReq(c,'/api/user/login',{username:c.username,password:c.password});c.token=pickToken(res)||'';c.tokenAt=Date.now();c.userId=String(pickUserId(res)||c.userId||'');if(!c.userId)throw new Error('登录成功但未返回用户标识')}}
async function fetchChannelData(c){return c.type==='sub2api'?fetchSub2Api(c):fetchNewApi(c)}
async function connectChannel(c){if(channelSyncing.has(c.id)||isRateLimited(c))return;channelSyncing.add(c.id);try{c.url=normBaseUrl(c.url,c.type);c.manual=cleanManual(c.manual,c.url);if(!chCanAuto(c))throw new Error('请填写站点地址、用户名和密码');if(c.token&&(c.type==='sub2api'||c.userId)){try{c.data=applyManual(await fetchChannelData(c),c);c.status='online';c.error=null;c.updatedAt=Date.now();return}catch(e){if(!/HTTP\s*401/.test(String(e?.message||e)))throw e;c.token='';c.tokenAt=0}}await loginChannel(c);c.data=applyManual(await fetchChannelData(c),c);c.status='online';c.error=null;c.updatedAt=Date.now()}catch(e){c.status='offline';c.error=chErr(e);c.data=null;c.updatedAt=Date.now()}finally{channelSyncing.delete(c.id);persistChannels()}}
async function fetchNewApi(c){const rg=todaySecRange();const [status,user,groups,data,topup]=await Promise.all([chReq(c,'/api/status'),chReq(c,'/api/user/self'),chReq(c,'/api/user/self/groups').catch(()=>null),chReq(c,`/api/data/self?start_timestamp=${rg.start}&end_timestamp=${rg.end}`).catch(()=>[]),chReq(c,'/api/user/topup/info').catch(()=>null)]);let amountQuote=null,amount=(topup?.amount_options&&topup.amount_options[0])||topup?.min_topup||1;try{const aq=await chReq(c,'/api/user/amount',{method:'POST',body:JSON.stringify({amount:Number(amount)})});amountQuote=aq?.data??aq}catch{}const curGroup=user?.group||'',g=groups?.[curGroup]||null,today=sumArr(data,'quota');return{kind:'newapi',user,status,groups:groups||{},currentGroup:curGroup,currentGroupRatio:g?.ratio??null,balanceRaw:user?.quota,usedRaw:user?.used_quota,todayRaw:today,todayReq:sumArr(data,'count'),todayTokens:sumArr(data,'token_used'),requestCount:user?.request_count,rechargeRatio:amountQuote?Number(amountQuote)/Number(amount):status?.price,topupInfo:topup,amountQuote}}
async function fetchSub2Api(c){const rg=todayDateRange();const [profile,usage,payment,groups]=await Promise.all([chReq(c,'/api/v1/auth/me'),chReq(c,'/api/v1/usage/dashboard/stats').catch(()=>null),chReq(c,'/api/v1/payment/config').catch(()=>null),chReq(c,'/api/v1/groups/available').catch(()=>[])]);return{kind:'sub2api',profile,usage,payment,groups:Array.isArray(groups)?groups:[],balance:profile?.balance,totalCost:usage?.total_actual_cost,todayCost:usage?.today_actual_cost,totalReq:usage?.total_requests,todayReq:usage?.today_requests,totalTokens:usage?.total_tokens,todayTokens:usage?.today_tokens,rechargeRatio:payment?.balance_recharge_multiplier,dateRange:rg}}
function channelMoney(c,key){const d=c.data||{};if(c.status!=='online'||!d)return null;if(c.type==='sub2api'){const m={balance:'balance',today:'todayCost',total:'totalCost'};return Number(d[m[key]])}if(key==='balance')return Number(d.balanceRaw)/(Number(d.status?.quota_per_unit)||500000);if(key==='today')return Number(d.todayRaw)/(Number(d.status?.quota_per_unit)||500000);if(key==='total')return Number(d.usedRaw)/(Number(d.status?.quota_per_unit)||500000);return null}
function renderChannelOverview(){const online=channels.filter(c=>c.status==='online').length,data=channels.filter(c=>c.status==='online'&&c.data);const sum=k=>data.reduce((n,c)=>{const v=channelMoney(c,k);return n+(Number.isFinite(v)?v:0)},0);return`<div class="overview"><div class="ov-grid"><div><div class="ov-k">在线渠道</div><div class="ov-v">${online}/${channels.length}</div></div><div><div class="ov-k">总余额</div><div class="ov-v">${fmtMoney(sum('balance'))}</div></div><div><div class="ov-k">今日消费</div><div class="ov-v">${fmtMoney(sum('today'))}</div></div><div><div class="ov-k">累计消费</div><div class="ov-v">${fmtMoney(sum('total'))}</div></div></div></div>`}
function channelSearchText(c){const d=c.data||{};return[c.name,c.url,c.username,c.type,d.user?.username,d.profile?.username,d.currentGroup,...channelGroups(c).map(g=>g.label)].join(' ').toLowerCase()}
function channelGroups(c){const d=c.data||{};if(c.type==='sub2api')return(d.groups||[]).map(g=>({label:g.name||String(g.id||''),ratio:g.rate_multiplier??g.ratio,title:'可用分组'})).filter(g=>g.label);return Object.entries(d.groups||{}).map(([k,v])=>({label:k,ratio:v?.ratio,title:v?.desc||'可用分组'}))}
function renderChannels(){const el=document.getElementById('channelPanel');if(!el)return;const q=channelQuery.trim().toLowerCase();let list=q?channels.filter(c=>channelSearchText(c).includes(q)):channels;const bar=`${renderChannelOverview()}<div class="search-row"><input class="fi" id="channelSearch" value="${esc(channelQuery)}" oninput="keepFocus(()=>{channelQuery=this.value;renderChannels()})" placeholder="搜索渠道 / 地址 / 账号">${ib('bp','新增渠道','showChModal()')}</div>`;if(!channels.length){el.innerHTML=bar+'<div class="empty">暂无渠道，点击新增渠道</div>';return}if(!list.length){el.innerHTML=bar+'<div class="empty">没有匹配的渠道</div>';return}el.innerHTML=bar+list.map(renderChannelCard).join('')}
let channelTipTimer=null;
function hideChannelTip(){const t=document.getElementById('chNameTip');if(t)t.remove();clearTimeout(channelTipTimer);channelTipTimer=null}
function channelTip(id,el,ev){ev?.stopPropagation?.();const c=channels.find(x=>x.id===id),d=c?.data||{};if(!c||!el)return;hideChannelTip();const type=c.type==='newapi'?'New API':'Sub2API',user=d.user?.username||d.profile?.username||c.username||'-',tip=document.createElement('div');tip.id='chNameTip';tip.className='name-tip';tip.innerHTML=`<strong>${type}</strong><span>${esc(user)}</span>`;tip.style.visibility='hidden';document.body.appendChild(tip);const r=el.getBoundingClientRect(),tw=tip.offsetWidth,th=tip.offsetHeight;let top=r.top-th-8;if(top<8)top=r.bottom+8;let left=Math.min(window.innerWidth-tw-8,Math.max(8,r.left+r.width/2-tw/2));tip.style.left=left+'px';tip.style.top=top+'px';tip.style.visibility='visible';channelTipTimer=setTimeout(hideChannelTip,3000)}
function renderChannelCard(c){const on=c.status==='online',loading=c.status===null,d=c.data||{},groups=channelGroups(c),site=esc(hrefUrl(c.url)),topup=hrefUrl(d.topupUrlManual||d.topupInfo?.pay_address||d.topupInfo?.topup_url||'',c.url);let body=loading?'<div class="qload"><span class="ld"></span>连接中</div>':on?renderChannelMetrics(c,d,topup):`<div class="qe">连接失败: ${esc(c.error||'未知错误')}</div>`;const groupLine=on&&groups.length?`<div class="group-line"><div class="chip-list">${groups.map(g=>`<span class="bdg" title="${esc(g.title||'')}">${esc(g.label)} ${fmtRatio(g.ratio)}</span>`).join('')}</div></div>`:'';return`<div class="ss sortable-card" draggable="true" ondragstart="cardDragStart('channel',${jsArg(c.id)},event)" ondragover="cardDragOver('channel',${jsArg(c.id)},event)" ondragleave="cardDragLeave(event)" ondrop="dropCard('channel',${jsArg(c.id)},event)" ondragend="cardDragEnd()"><div class="sb cpa-head ch-head"><div class="cpa-main ch-main"><div class="cpa-title ch-title"><span class="dot ${on?'on':'off'}"></span><button class="cpa-name ch-name" onclick="channelTip('${c.id}',this,event)" title="查看渠道信息" aria-label="查看渠道信息">${esc(c.name)}</button><a class="site-link cpa-site ch-site" href="${site}" target="_blank" rel="noopener noreferrer">${esc(maskUrl(c.url))}</a></div><div class="cpa-meta ch-meta">${body}</div></div><div class="s-act cpa-actions ch-actions">${ib('bs','密钥',`showChKeys('${c.id}')`,!on?'disabled':'')}${topup?ib('bs','充值',`window.open(${jsArg(topup)},'_blank','noopener')`):ib('bs','充值','', 'disabled')}${ib('bs','刷新',`refreshChannel('${c.id}')`,chRefreshing.has(c.id)?'disabled':'')}${ib('bs','更多',`toggleChMenu('${c.id}',event)`)}${renderChMenu(c.id)}</div>${groupLine}</div></div>`}
function renderChMenu(id){return`<div class="srv-menu hidden" id="chMenu_${id}"><button class="srv-menu-item" onclick="showChModal('${id}')">${icon('i-edit')}<span>编辑</span></button><button class="srv-menu-item danger" onclick="delCh('${id}')">${icon('i-trash')}<span>删除</span></button></div>`}
function toggleChMenu(id,ev){ev?.stopPropagation?.();const el=document.getElementById('chMenu_'+id),next=el&&!el.classList.contains('hidden')?null:id;document.querySelectorAll('.srv-menu').forEach(x=>x.classList.add('hidden'));chMenuId=next;srvMenuId=null;if(next)document.getElementById('chMenu_'+next)?.classList.remove('hidden')}
function renderMetric(label,value,help=''){return`<div class="metric-card"><div class="metric-label">${label}</div><div class="metric-value">${value}</div>${help?`<div class="metric-help">${help}</div>`:''}</div>`}
function renderChannelMetrics(c,d,topup){if(c.type==='sub2api')return renderSub2Metrics(d,topup);return renderNewApiMetrics(d,topup)}
function renderRechargeRatio(label){return`比例 <strong>${esc(label)}</strong>`}
function renderNewApiMetrics(d,topup){const s=d.status||{},rr=d.rechargeRatioManual||fmtRatio(d.rechargeRatio);return`<div class="channel-line"><span>余额 <strong>${fmtNewQuota(d.balanceRaw,s)}</strong></span><span>今日 <strong>${fmtNewQuota(d.todayRaw,s)}</strong></span><span>累计 <strong>${fmtNewQuota(d.usedRaw,s)}</strong></span><span>${renderRechargeRatio(rr)}</span></div>`}
function renderSub2Metrics(d,topup){const rr=d.rechargeRatioManual||fmtRatio(d.rechargeRatio);return`<div class="channel-line"><span>余额 <strong>${fmtMoney(d.balance)}</strong></span><span>今日 <strong>${fmtMoney(d.todayCost)}</strong></span><span>累计 <strong>${fmtMoney(d.totalCost)}</strong></span><span>${renderRechargeRatio(rr)}</span></div>`}
async function refreshChannels(){await Promise.allSettled(channels.map(c=>refreshChannel(c.id,true)));renderData()}
async function refreshChannel(id,silent){const c=channels.find(x=>x.id===id);if(!c||chRefreshing.has(id))return;chRefreshing.add(id);if(!silent)renderData();try{await connectChannel(c)}finally{chRefreshing.delete(id);if(!silent)renderData()}}
function showChModal(id){editChId=id||null;chSaving=false;chMenuId=null;document.querySelectorAll('.srv-menu').forEach(x=>x.classList.add('hidden'));const c=channels.find(x=>x.id===id),m=c?.manual||{};document.getElementById('chMt').textContent=c?'编辑渠道':'添加渠道';document.getElementById('chName').value=c?.name||'';document.getElementById('chType').value=c?.type||'newapi';document.getElementById('chUrl').value=c?.url||'';document.getElementById('chUser').value=c?.username||'';document.getElementById('chPass').value=c?.password||'';document.getElementById('chTopupUrl').value=m.topupUrl||'';document.getElementById('chRechargeRatio').value=m.rechargeRatio||'';setChSaveBusy(false);document.getElementById('chModal').classList.remove('hidden')}
function hideChModal(){if(chSaving)return;document.getElementById('chModal').classList.add('hidden');editChId=null;setChSaveBusy(false)}
function setChSaveBusy(v){chSaving=v;const b=document.getElementById('chSaveBtn');if(b){b.disabled=v;b.innerHTML=v?'<span class="ld" style="width:14px;height:14px;border-width:2px"></span>':icon('i-check');b.dataset.iconized='保存';b.classList.add('icon-only','icon-btn')}}
function saveCh(){if(chSaving)return;const name=document.getElementById('chName').value.trim(),type=document.getElementById('chType').value,url=normBaseUrl(document.getElementById('chUrl').value,type),username=document.getElementById('chUser').value.trim(),password=document.getElementById('chPass').value,manual=cleanManual({topupUrl:document.getElementById('chTopupUrl').value,rechargeRatio:document.getElementById('chRechargeRatio').value},url);if(!name){alert('请填写名称');return}if(!url||!username||!password){alert('请填写站点地址、用户名和密码');return}setChSaveBusy(true);let target=null,isEdit=!!editChId;try{if(editChId){target=channels.find(x=>x.id===editChId);if(target){Object.assign(target,{name,type,url,username,password,manual,userId:'',token:'',tokenAt:0,status:null,data:null,error:null})}}else{target={id:'ch_'+Date.now(),name,type,url,username,password,manual,userId:'',token:'',tokenAt:0,status:null,data:null,error:null};channels.push(target)}if(!target)throw new Error('渠道不存在');persistChannels();document.getElementById('chModal').classList.add('hidden');editChId=null;showToast(isEdit?'渠道已保存，正在同步':'渠道已添加，正在同步');renderCur()}catch(e){showToast('保存失败: '+(e.message||e));renderCur();return}finally{setChSaveBusy(false)}connectChannel(target).then(()=>renderCur()).catch(()=>renderCur())}
function delCh(id){const c=channels.find(x=>x.id===id);if(!c)return;if(!confirm(`确定要删除渠道 "${c.name}" 吗？`))return;channels=channels.filter(x=>x.id!==id);persistChannels();showToast('渠道已删除');renderCur()}

async function showChKeys(id){const c=channels.find(x=>x.id===id);if(!c)return;chKeyId=id;chKeys=[];chKeyFull={};chKeyShown={};chKeyGroups=[];chKeyEditId=null;document.getElementById('chKeyTitle').textContent='— '+c.name;document.getElementById('chKeyLoading').classList.remove('hidden');document.getElementById('chKeyContent').classList.add('hidden');document.getElementById('chKeyContent').innerHTML='';document.getElementById('chKeyModal').classList.remove('hidden');await loadChKeys()}
function hideChKeys(){document.getElementById('chKeyModal').classList.add('hidden');chKeyId=null;chKeys=[];chKeyFull={};chKeyShown={};chKeyGroups=[];chKeyEditId=null}
function chKeyEndpoint(c,qs=''){return c.type==='sub2api'?`/api/v1/keys${qs}`:`/api/token/${qs}`}
function chKeyListPath(c){return c.type==='sub2api'?'/api/v1/keys?page=1&page_size=100':'/api/token/?p=1&size=100'}
function chEndpointUrl(c){return joinUrl(c.url,'/v1')}
function chKeyGroupName(k){const g=k.group;if(g&&typeof g==='object')return String(g.name||g.id||'');return String(g||k.Group?.name||'')}
function chKeyStatus(k){const s=k.status;if(typeof s==='string')return s==='active'?'启用':s==='inactive'?'禁用':s;return{1:'启用',2:'禁用',3:'过期',4:'耗尽',0:'禁用'}[Number(s)]||'未知'}
function chKeyStatusClass(k){return chKeyStatus(k)==='启用'?'bdg-ok':'bdg-err'}
function normalizeChKey(c,k){if(c.type==='sub2api'){const g=k.group||k.Group||{};const total=Number(k.quota)||0,used=Number(k.quota_used)||0;return{id:k.id,name:k.name||'未命名密钥',key:k.key||'',status:k.status,group:g.name||'',groupId:k.group_id||g.id||'',unlimited_quota:total<=0,remain_quota:Math.max(total-used,0),used_quota:used,raw:k}}return{...k,raw:k}}
async function loadChKeyGroups(c){const known=channelGroups(c);if(c.type==='sub2api'){const gs=await chReq(c,'/api/v1/groups/available').catch(()=>[]);chKeyGroups=(Array.isArray(gs)?gs:[]).map(g=>{const label=g.name||String(g.id),m=known.find(x=>x.label===label);return{label,id:g.id,ratio:g.rate_multiplier??g.ratio??m?.ratio}}).filter(g=>g.label);return}chKeyGroups=known.map(g=>({label:g.label,id:g.label,ratio:g.ratio}))}
async function loadChKeys(){const c=channels.find(x=>x.id===chKeyId),box=document.getElementById('chKeyContent');if(!c||!box)return;chKeysLoading=true;try{if(c.status!=='online')await connectChannel(c);await loadChKeyGroups(c);const d=await chReq(c,chKeyListPath(c));chKeys=unwrapItems(d).map(k=>normalizeChKey(c,k));renderChKeys()}catch(e){box.innerHTML=`<div class="empty">${esc(chErr(e))}</div>`}finally{chKeysLoading=false;document.getElementById('chKeyLoading').classList.add('hidden');box.classList.remove('hidden');scheduleIconize()}}
function chKeyGroupInfo(c,name){const n=String(name||'');return chKeyGroups.find(g=>g.label===n)||channelGroups(c).find(g=>g.label===n)||null}
function chKeyGroupLabel(c,name){const info=chKeyGroupInfo(c,name),label=name||'未分组',ratio=fmtRatio(info?.ratio);return ratio==='-'?label:`${label} ${ratio}`}
function chKeyGroupOptions(c,current=''){return[...new Set([...chKeyGroups.map(g=>g.label),current].filter(Boolean))]}
function renderChKeyToolbar(c){const opts=chKeyGroupOptions(c);return`<div class="key-create"><input class="fi" id="newKeyName" placeholder="新密钥名称" value=""><select class="fi" id="newKeyGroup" ${opts.length?'':'disabled'}>${opts.length?opts.map(o=>`<option value="${esc(o)}">${esc(chKeyGroupLabel(c,o))}</option>`).join(''):'<option value="">无可用分组</option>'}</select>${ib('bp','新增',`createChKey()`,opts.length?'':'disabled')}</div>`}
function renderChKeys(){const box=document.getElementById('chKeyContent'),c=channels.find(x=>x.id===chKeyId);if(!box||!c)return;const list=chKeys.length?chKeys.map(k=>renderChKeyItem(c,k)).join(''):'<div class="empty">暂无密钥</div>';box.innerHTML=endpointRow(chEndpointUrl(c))+renderChKeyToolbar(c)+list;scheduleIconize()}
function renderChKeyItem(c,k){const id=String(k.id),full=chKeyFull[id]||'',shown=!!chKeyShown[id],secret=shown?(full||k.key||''):'',keyText=shown?esc(secret||'未返回密钥'):maskSecret(k.key||full),group=chKeyGroupName(k),editing=String(chKeyEditId)===id,opts=chKeyGroupOptions(c,group),nameId=keyDomId('keyName',id),groupId=keyDomId('chg',id);const title=editing?`<input class="fi key-edit-name" id="${nameId}" value="${esc(k.name||'')}">`:`<span class="key-name">${esc(k.name||'未命名密钥')}</span>`;const groupView=editing?`<select class="fi key-edit-group" id="${groupId}">${opts.map(o=>`<option value="${esc(o)}" ${o===group?'selected':''}>${esc(chKeyGroupLabel(c,o))}</option>`).join('')}</select>`:`<span class="bdg key-group">${esc(chKeyGroupLabel(c,group))}</span>`;const actions=editing?`${ib('bp','保存',`saveChKey(${jsArg(id)})`)}${ib('bs','取消',`cancelChKeyEdit()`)}`:`${ib('bs','复制',`copyChKey(${jsArg(id)})`)}${ib('bs',shown?'隐藏密钥':'显示密钥',`toggleChKey(${jsArg(id)})`)}${ib('bs','编辑',`editChKey(${jsArg(id)})`)}${ib('bd','删除',`deleteChKey(${jsArg(id)})`)}`;return`<div class="key-row"><div class="key-info"><div class="key-top">${title}<span class="bdg ${chKeyStatusClass(k)}">${esc(chKeyStatus(k))}</span>${groupView}</div><code class="key-secret ${shown?'show':''}">${keyText}</code></div><div class="ch-actions key-actions">${actions}</div></div>`}
function editChKey(id){chKeyEditId=id;renderChKeys()}
function cancelChKeyEdit(){chKeyEditId=null;renderChKeys()}
function groupIdForName(name){return chKeyGroups.find(g=>g.label===name)?.id}
function groupIdPayload(v){return/^\d+$/.test(String(v))?Number(v):v}
function keyPayload(c,k,name,group){if(c.type==='sub2api'){const gid=groupIdForName(group),hasGroup=gid!==undefined&&gid!==null&&gid!=='';return{name:name||k.name||'key',quota:Number(k.raw?.quota??k.remain_quota??0)||0,ip_whitelist:Array.isArray(k.raw?.ip_whitelist)?k.raw.ip_whitelist:[],...(hasGroup?{group_id:groupIdPayload(gid)}:{})}}return{...k.raw,...k,name:name||k.name,group}}
async function ensureChKeyFull(id){const c=channels.find(x=>x.id===chKeyId),k=chKeys.find(x=>String(x.id)===String(id));if(!c||!k)return'';if(chKeyFull[id])return chKeyFull[id];if(c.type==='newapi'){const d=await chReq(c,`/api/token/${id}/key`,{method:'POST'});chKeyFull[id]=d?.key||d?.data?.key||''}else chKeyFull[id]=k.key||'';if(!chKeyFull[id])throw new Error('未返回密钥');return chKeyFull[id]}
async function toggleChKey(id){try{if(chKeyShown[id]){chKeyShown[id]=false;renderChKeys();return}await ensureChKeyFull(id);chKeyShown[id]=true;renderChKeys()}catch(e){showToast('获取密钥失败: '+chErr(e))}}
async function copyChKey(id){try{const key=await ensureChKeyFull(id);if(!key)return;copyText(key)}catch{copyText(chKeyFull[id]||'')}}
async function saveChKey(id){const c=channels.find(x=>x.id===chKeyId),k=chKeys.find(x=>String(x.id)===String(id)),sel=document.getElementById(keyDomId('chg',id)),inp=document.getElementById(keyDomId('keyName',id));if(!c||!k||!sel)return;try{const body=keyPayload(c,k,inp?.value?.trim(),sel.value);await chReq(c,c.type==='sub2api'?`/api/v1/keys/${id}`:'/api/token/',{method:'PUT',body:JSON.stringify(body)});showToast('密钥已保存');chKeyEditId=null;await loadChKeys()}catch(e){showToast('保存失败: '+chErr(e))}}
async function createChKey(){const c=channels.find(x=>x.id===chKeyId),name=document.getElementById('newKeyName')?.value?.trim()||'new-key',group=document.getElementById('newKeyGroup')?.value||'';if(!c)return;if(!group){showToast('没有可用分组');return}try{let body;if(c.type==='sub2api'){const gid=groupIdForName(group);if(gid===undefined||gid===null||gid===''){showToast('请选择有效分组');return}body={name,quota:0,ip_whitelist:[],expires_in_days:0,group_id:groupIdPayload(gid)}}else body={name,group,remain_quota:0,expired_time:-1,unlimited_quota:true,model_limits_enabled:false,model_limits:'',allow_ips:'',cross_group_retry:false};await chReq(c,c.type==='sub2api'?'/api/v1/keys':'/api/token/',{method:'POST',body:JSON.stringify(body)});showToast('密钥已新增');await loadChKeys()}catch(e){showToast('新增失败: '+chErr(e))}}
async function deleteChKey(id){const c=channels.find(x=>x.id===chKeyId),k=chKeys.find(x=>String(x.id)===String(id));if(!c||!k)return;if(!confirm(`确定删除密钥 "${k.name||id}" 吗？`))return;try{await chReq(c,c.type==='sub2api'?`/api/v1/keys/${id}`:`/api/token/${id}`,{method:'DELETE'});showToast('密钥已删除');await loadChKeys()}catch(e){showToast('删除失败: '+chErr(e))}}

/* ============ API KEY MANAGEMENT ============ */
let akSrvId=null,akKeys=[];
function showApiKeyModal(sid){akSrvId=sid;const s=servers.find(x=>x.id===sid);if(!s||s.status!=='online')return;document.getElementById('akSrvName').textContent='— '+s.name;document.getElementById('akLoading').classList.remove('hidden');document.getElementById('akContent').classList.add('hidden');document.getElementById('akNewKey').value='';document.getElementById('apiKeyModal').classList.remove('hidden');fetchApiKeys()}
function hideApiKeyModal(){document.getElementById('apiKeyModal').classList.add('hidden');akSrvId=null;akKeys=[]}
async function fetchApiKeys(){const s=servers.find(x=>x.id===akSrvId);if(!s)return;try{const d=cpaJson(await cpaHttp(cpaUrl(s,'/api-keys'),{headers:{'Authorization':cpaAuth(s)}}));akKeys=d['api-keys']||[];renderAkList()}catch(e){akKeys=[];renderAkList();showToast('获取失败: '+e.message)}finally{document.getElementById('akLoading').classList.add('hidden');document.getElementById('akContent').classList.remove('hidden')}}
function renderAkList(){const el=document.getElementById('akList'),s=servers.find(x=>x.id===akSrvId);if(!el)return;const head=s?endpointRow(cpaEndpointUrl(s)):'';if(!akKeys.length){el.innerHTML=head+'<div style="text-align:center;padding:20px;color:var(--t2);font-size:12px">暂无 API Key</div>';return}
el.innerHTML=head+akKeys.map((k,i)=>{const masked=k.length>12?k.slice(0,4)+'****'+k.slice(-4):k.slice(0,2)+'****';return`<div class="ak-row" id="akr_${i}"><span class="ak-val"><span class="ak-masked">${esc(masked)}</span><span class="ak-full">${esc(k)}</span></span><button class="b bs bsm" onclick="toggleAkFull(${i})" title="显示/隐藏">👁</button><button class="b bs bsm" onclick="copyAk(${i})" title="复制">📋</button><button class="b bd bsm" onclick="delAk(${i})" title="删除">✕</button></div>`}).join('')}
function toggleAkFull(i){const r=document.getElementById('akr_'+i);if(r)r.classList.toggle('show-full')}
function copyAk(i){if(!akKeys[i])return;copyText(akKeys[i])}
async function delAk(i){const s=servers.find(x=>x.id===akSrvId);if(!s)return;try{await cpaHttp(cpaUrl(s,'/api-keys',{index:i}),{method:'DELETE',headers:{'Authorization':cpaAuth(s)}});showToast('已删除');await fetchApiKeys()}catch(e){showToast('删除失败: '+e.message)}}
async function addApiKey(){const s=servers.find(x=>x.id===akSrvId);if(!s)return;const v=document.getElementById('akNewKey').value.trim();if(!v){showToast('请输入 API Key');return}const newKeys=[...akKeys,v];try{await cpaHttp(cpaUrl(s,'/api-keys'),{method:'PUT',headers:{'Authorization':cpaAuth(s),'Content-Type':'application/json'},body:JSON.stringify(newKeys)});document.getElementById('akNewKey').value='';showToast('已添加');await fetchApiKeys()}catch(e){showToast('添加失败: '+e.message)}}
function genApiKey(){const cs='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';const a=new Uint8Array(17);crypto.getRandomValues(a);const k='sk-'+Array.from(a,b=>cs[b%cs.length]).join('');document.getElementById('akNewKey').value=k}

/* ============ SETTINGS MODAL ============ */
let stSrvId=null;
function showSrvSettings(sid){stSrvId=sid;const s=servers.find(x=>x.id===sid);if(!s||s.status!=='online')return;document.getElementById('stSrvName').textContent='— '+s.name;document.getElementById('stLoading').classList.remove('hidden');document.getElementById('stContent').classList.add('hidden');document.getElementById('settingsModal').classList.remove('hidden');loadSettingsCfg()}
function hideSettingsModal(){document.getElementById('settingsModal').classList.add('hidden');stSrvId=null}
async function loadSettingsCfg(){const s=servers.find(x=>x.id===stSrvId);if(!s)return;const cfg={};const endpoints=[{key:'proxy-url',path:'/proxy-url',label:'代理 URL',type:'text',placeholder:'例如: socks5://user:pass@host:1080/'},{key:'request-retry',path:'/request-retry',label:'请求重试次数',type:'number',placeholder:'0'},{key:'routing/strategy',path:'/routing/strategy',label:'路由策略',type:'select',options:[{v:'round-robin',l:'round-robin (轮询)'},{v:'fill-first',l:'fill-first (填满优先)'}]}];
await Promise.allSettled(endpoints.map(async ep=>{try{const d=cpaJson(await cpaHttp(cpaUrl(s,ep.path),{headers:{'Authorization':cpaAuth(s)}}));cfg[ep.key]=d[ep.key]??d.value??''}catch{cfg[ep.key]=null}}));
const c=document.getElementById('stContent');if(!c)return;let h='';endpoints.forEach(ep=>{const v=cfg[ep.key],cur=v===null?'不支持':String(v||'未设置');h+=`<div class="setting-card"><div class="setting-head"><div><div class="setting-label">${ep.label}</div><div class="setting-current">当前：${esc(cur)}</div></div></div>`;
if(v===null){h+=`<div class="setting-empty">此服务端不支持该配置</div>`}else if(ep.type==='select'){h+=`<div class="setting-control"><select class="fi" id="st_${ep.key}">${ep.options.map(o=>`<option value="${esc(o.v)}" ${String(v)===o.v?'selected':''}>${esc(o.l)}</option>`).join('')}</select><button class="b bp icon-btn keep-icon" onclick="saveStCfg('${ep.key}','${ep.path}')" title="保存" aria-label="保存">${icon('i-check')}</button></div>`}else{h+=`<div class="setting-control"><input class="fi" id="st_${ep.key}" type="${ep.type}" value="${esc(String(v))}" placeholder="${ep.placeholder}"><button class="b bp icon-btn keep-icon" onclick="saveStCfg('${ep.key}','${ep.path}')" title="保存" aria-label="保存">${icon('i-check')}</button></div>`}
h+='</div>'});c.innerHTML=h;document.getElementById('stLoading').classList.add('hidden');c.classList.remove('hidden')}
async function saveStCfg(key,path){const s=servers.find(x=>x.id===stSrvId);if(!s)return;const inp=document.getElementById('st_'+key);if(!inp)return;let v=key==='proxy-url'?cleanUrlText(inp.value):inp.value.trim();if(inp.type==='number')v=parseInt(v)||0;try{await cpaHttp(cpaUrl(s,path),{method:'PUT',headers:{'Authorization':cpaAuth(s),'Content-Type':'application/json'},body:JSON.stringify({value:v})});showToast('保存成功');loadSettingsCfg()}catch(e){showToast('保存失败: '+e.message)}}
